### ISSUE TITLE
What about Dynamic 365 connector 

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#100]
What about connector to Dynamic 365 CRM in Same AAD?
Better yet connector to Common Data Services in Same AAD?

**Comment by monaray97** [comment]
Hi @Ofer-Gal apologies for the delay. Could you elaborate on your ask for Dynamics 365 connector? What exactly is your business need? Feel free to follow up at MicrosoftGraphConnectorsFeedback@service.microsoft.com.
