### ISSUE TITLE
Enterprise Website Connector - Data source isn't available error

### ISSUE THREAD

**Issue by arnieraju** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#102]
I am using the Enterprise Websites connector in the Search & Intelligence admin center to index some publicly accessible websites.

I have managed to add 2 websites and have these successfully crawled and indexed.  These are https://ppl.app.uq.edu.au
and https://staff.uq.edu.au

I have 2 more sites which I am able to successfully configure the connectors however once they are published I am receiving a connection state status of Failed on both, and the following error: "The data source isn't available. Check your internet connection or make sure the data source is still accessible by the connector."

![image](https://user-images.githubusercontent.com/1208184/100040434-fe164380-2e52-11eb-97c3-148f623fa736.png)

These sites are https://support.staff.uq.edu.au and https://support.my.uq.edu.au which are both accessible on the web.

Is there anywhere I can get further information to troubleshoot the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a96fc6-83a6-c5ff-5011-b1c45c5b4cd9
* Version Independent ID: 6ea63426-a507-e898-4a64-c35610c639cf
* Content: [Connectors feedback page](https://docs.microsoft.com/en-us/microsoftsearch/connectors-feedback)
* Content Source: [MicrosoftSearch/connectors-feedback.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/connectors-feedback.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by monaray97** [comment]
Hi @arnieraju, sorry you are facing this error. This is a currently known issue. A fix for this has been checked in and is being deployed to prod today. This issue will most likely go away if your connections try to sync again later today or tomorrow. Please let me know if you continue to face this error after a few days.

**Comment by arnieraju** [comment]
@monaray97 - thanks for checking in with me and for the update.  I can confirm after kicking off the index for each of those connections the connections have moved from a Red 'Errored' state to a Green 'Ready' state.  

However now in the developer tenancy my quota has dropped from 2,000,000 to 0 - so I am unable to verify the indexing is working.

![image](https://user-images.githubusercontent.com/1208184/102181389-2fd07680-3ef6-11eb-9261-17829b4b43d5.png)

Do you have any advice on the change in available quotas and whether this will be re-instated for developer tenancies?

Thanks again for your time on this one!

**Comment by monaray97** [comment]
Hi @arnieraju, if you were using Graph connectors in preview, you will not incur any costs until Feb 2021. This page has detailed information with regards to our licensing requirements for using Graph connectors - https://docs.microsoft.com/en-us/microsoftsearch/licensing.

**Comment by arnieraju** [comment]
Thanks for the quick response @monaray97
The issue I have just hit during testing is that I no longer a quota available in my tenant, and I don't know whether this is related, but when I check the "Extra Graph Connector Capacity" option in Purchase services it now tells me "You are not eligible to acquire this product"

Previously this option was available.  

I just wanted to check in to see whether this is as a result of it being in preview, or whether there is something I need to configure to re-enable the quota etc.

![image](https://user-images.githubusercontent.com/1208184/102287958-3824c200-3f87-11eb-8602-cdf6c520cd5c.png)

**Comment by monaray97** [comment]
@arnieraju Apologies for the delay in getting back to you. Are you still facing this issue?
