### ISSUE TITLE
GCCH available?

### ISSUE THREAD

**Issue by jordonthreadgill** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#103]
I am not able to find supporting documentation for this solution around GCCH tenants.  That said, there is no documentation saying it's not (yet) supported either.  Can someone confirm what the status of this feature is for GCCH customers?  In the tenant that I have access to, the Search & Intelligence options are not available in the admin center.

**Comment by jeffkizn** [comment]
Microsoft Search is not available in US Gov environments including GCCH. We are working on the roadmap for those environments and will post updates to the Office roadmap soon.

**Comment by jordonthreadgill** [comment]
Thank you sir!
