### ISSUE TITLE
Different fields in acronyms template

### ISSUE THREAD

**Issue by SydneyWaterRat** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#104]
This page documents the CSV fields for the bulk import of acronyms. When you use the link:
Download acronyms template (.csv)
accessed on the page
https://admin.microsoft.com/Adminportal/Home?#/MicrosoftSearch/acronyms
then the fields are:

Acronym (Mandatory)
Expansion (Mandatory)
Url
Description
State (Mandatory)
Last Modified
Last Modified By
Id

the page lists:

Acronym (mandatory) | Expansion (mandatory) | Description | Source | State (mandatory)

which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd51764-80a7-b404-50bd-b492b193dab2
* Version Independent ID: 62a6858b-81a3-bafa-4bcc-3bb2a951c654
* Content: [Manage Acronym answers in Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms)
* Content Source: [MicrosoftSearch/manage-acronyms.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-acronyms.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by RakeshMSFT** [comment]
@SydneyWaterRat The fields mentioned on the .csv file downloaded from Admin center are the correct ones. On the document "Manage Acronyms answers in Microsoft search" it shows older fields which needs to be updated. Thanks for pointing this out, I will be working with my team to bring this update to the document soon. Thank for using our feature.

**Comment by jeffkizn** [comment]
The documentation has been updated.
