### ISSUE TITLE
Bookmark Import - how to create ID in column from CSV template? 

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#109]
In O365 Admin Center - Search & intelligence - Bookmarks - Import, there is a template for bookmarks import, called BookmarkImportTemplate.
The las column is ID, which are in the format 289fd8cb-a08a-4610-a7ac-5c02842662ad.
When using the import feature, we have to construct our own bookmarks. 
The question is, how to construct the last column, for ID's ? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96809b75-c20f-bfcf-9a69-7793f51172bf
* Version Independent ID: 48f803b7-3759-f040-895f-45e1b6559768
* Content: [Make content easy to find with Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/make-content-easy-to-find)
* Content Source: [MicrosoftSearch/make-content-easy-to-find.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/make-content-easy-to-find.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by tanaybaldua** [comment]
Hi Team

I understand your query and the simple answer is you dont have to create an ID if you are creating a new bookmark via import. On import, the system will create one itself.
If you are trying to amend an existing bookmark, then kindly refrain from changing the ID as the system will update based on the ID mapped to existing bookmark.

Hope this helps.

Regards
Tanay

**Comment by tanaybaldua** [comment]
I am unable to close the issue. @danone1985 If you are satisfied and ok, please close it
