### ISSUE TITLE
Extra Graph Connector Capacity not visible for me

### ISSUE THREAD

**Issue by frank9843** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#110]
When trying to follow the steps to buy extra graph connector capacity, under add-ins, the option "Extra graph connector capacity" is not visible to me. I am a tenant admin.
Is the "Extra graph connector capacity" only available under certain conditions? Or is this article outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @rsamai
* Microsoft Alias: **rusamai**

**Comment by rsamai** [comment]
@frank9843 Which tenant sku (E1, E3, E5, A3, A5) are you trying? Can you please share a screenshot?

**Comment by frank9843** [comment]
Under E3 (which I've since enabled) I can see this option available. I'll email you the screenshot.

**Comment by frank9843** [comment]
@rsamai The email address you provided doesn't exist. Did you make a typo? Emails to this address are bouncing with an "address does not exist" message.

**Comment by rsamai** [comment]
@frank9843  You're right, this is the correct email: 
Microsoft Graph Connectors Feedback <MicrosoftGraphConnectorsFeedback@service.microsoft.com>
