### ISSUE TITLE
Why have you removed the ability to connect to a SharePoint site for a vertical?

### ISSUE THREAD

**Issue by Heidi-Connor** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#111]
The document now states "You can't create a vertical for content that resides in SharePoint", however, previously you had a specific connector for SharePoint. Can you explain  more why the capability was removed and if you intend to include it again later?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-US/microsoftsearch/customize-search-page)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @jypal
* Microsoft Alias: **jeffkizn**

**Comment by jypal6** [comment]
The statement "You can't create a vertical for content that resides in SharePoint" refers to SharePoint as a content source i.e. SharePoint data already present in Microsoft search index. The capability to add verticals for this content is not yet available in Microsoft Search and is a part of an ongoing effort. Refer to the following talk for more details: [Make Microsoft Search uniquely yours with new](https://techcommunity.microsoft.com/t5/video-hub/make-microsoft-search-uniquely-yours-with-new-customization/m-p/1696763) . 
Are you referring to the Connectors present in Classic Search? Can you provide more details around the connector for SharePoint.

**Comment by jypal6** [comment]
@Heidi-Connor Do let me know if the above addresses your question.

**Comment by bryllyg** [comment]
Hi, Sorry for the delayed reply, I appreciate the information! Yes, it did indeed answer my question. I will be patient and wait for that functionality to get rolled in. I saw a video (somewhere! can't seem to find it now) where it showed SharePoint as an option for the search vertical and that got me going off in the wrong direction, thinking the feature had been deprecated. Thank you so much for the information!

**Comment by jypal6** [comment]
Closing this issue.
