### ISSUE TITLE
Index quota expiration

### ISSUE THREAD

**Issue by dumardale** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#112]
[Enter feedback here]

In this article it is stated that for customers using the feature in preview, the quota is expiring in February 2021 however the following message is displayed in the admin portal:

"Your organization is out of space for Index. You must free up some space by deleting some connections"

---
![image](https://user-images.githubusercontent.com/75721489/101601234-1f576200-3a05-11eb-845c-c3f082595a19.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e785be0b-a0aa-13f2-21b9-2dd7defd39ea
* Version Independent ID: cba8efaa-5cdb-0c2d-db36-df4b740694c5
* Content: [Manage Microsoft Graph Connectors for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-connector#feedback)
* Content Source: [MicrosoftSearch/manage-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by monaray97** [comment]
Hi @dumardale, this message was posted to your tenant in error. The fix for this will be deployed early next week. Please comment on this thread if you continue to see it by the end of the next week.
