### ISSUE TITLE
Microsoft search != modern SharePoint search

### ISSUE THREAD

**Issue by bostonmusicdave** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#12]
MIcrosoft search defaults to a disabled state in office 365 tenants today and requires admins to flip it on under services.  Without this enabled, SharePoint home uses the modern personalized graph based SharePoint search but not the new capabilities shown as a part of Microsoft Search. 

The modern SharePoint search on sphome benefit from enabling Microsoft Search.

Once an admin turns on Microsoft search then the bookmarks, faqs, and locations from the Microsoft search admin center light up on SharePoint home. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f13f-b678-3cb0-58e3-4e798201aa7a
* Version Independent ID: fe5470d4-8703-2ce3-7cf6-b53416f13199
* Content: [Get started with Microsoft Search in SharePoint Online](https://docs.microsoft.com/en-us/MicrosoftSearch/get-started-search-in-sharepoint-online#feedback)
* Content Source: [MicrosoftSearch/get-started-search-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-started-search-in-sharepoint-online.md)
* Service: **mssearch**
* GitHub Login: @tlarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
In Targeted Release, Microsoft Search is on by default for the apps that currently support Microsoft Search, including SharePoint.

**Comment by WendyStidmon** [comment]
Thank you for your feedback! We are in the process of rolling out Microsoft Search in Bing to all supported tenants at this time and it will be turned on by default. Previous for the preview version, you did need to explicitly turn this feature on.

Cheers,
-Wendy
