### ISSUE TITLE
clarify license requirement for MS search connector quota

### ISSUE THREAD

**Issue by Stephen-Colie-SWO** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#120]
What licenses are valid?
What licenses give Graph connector quota?
I looked and couldn't find answers to these questions in the documentation. MS Support confirmed an E5 license is required. The article refers to E5 licenses as valid, but it seems to imply other licenses may be valid. Is that the case?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @rsamai
* Microsoft Alias: **rusamai**

**Comment by monaray97** [comment]
Hi @Stephen-Colie-SWO, thank you for your question. All licenses are valid (i.e. users with any M365 or O365 license can see connector data search results). However, only E5 licenses come with built-in quota. Please let me know if anything is still unclear.

**Comment by RyanMorash** [comment]
@monaray97 Do the education equivalent M365 A5 licenses also include the built-in quota

**Comment by monaray97** [comment]
@RyanMorash Unfortunately A5 licenses do not come with built-in quota.
