### ISSUE TITLE
What are the pre-requisites for using Graph connectors?

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#121]
Our company tenant doesn't have the Connectors tab in M365 Admin | Settings | Search & intelligence.
The need for M365 E5 licenses was mentioned in a recent Project Cortex related call, but we have 100 E5s.
Are there any other requirements, that should be documented, before the tab will appear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8979c8b-d009-2611-c803-61353f4aae0a
* Version Independent ID: eff84f91-933e-b3e7-875b-29acbf837e46
* Content: [Configure your Microsoft-built connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/configure-connector)
* Content Source: [MicrosoftSearch/configure-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/configure-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by monaray97** [comment]
Hi @Craig-Humphrey, we are currently in the middle of our rollout of Connectors to all tenants worldwide. Currently, your tenant must be opted into Targeted Release to see the Connectors tab in the M365 admin center. By the end of February when our WW rollout completes, all tenants should see the Connectors tab in the M365 admin center.

Each Microsoft 365 or Office 365 E5 license includes 500 items of index quota. If you'd like to purchase addition quota you can do so by following these instructions - https://docs.microsoft.com/en-us/microsoftsearch/licensing. 

Please let me know if you have any other questions.

**Comment by Craig-Humphrey** [comment]
Thanks @monaray97 there had been no mention of targeted, so I assumed it was GA.

Is it possible that the documentation could be updated to reflect the rollout status?  This isn't specific to this one page/service.  I know some pages end up with some form of "In Preview" text, but it would be really handy for documentation to reflect the rollout status of the service/application it's referring to.

Thanks!
Craig

**Comment by monaray97** [comment]
Thanks for the feedback @Craig-Humphrey. My team will work on updating the documentation so it is clearer. Thanks!
