### ISSUE TITLE
Chromium Edge

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#122]
Please update this documentation for Chromium Edge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93ac9d4-2e68-9a5d-d31b-e655775755cd
* Version Independent ID: 11bee2c8-1656-1915-ba21-83d4bfa6d525
* Content: [Set default browser](https://docs.microsoft.com/en-us/microsoftsearch/set-default-browser)
* Content Source: [MicrosoftSearch/set-default-browser.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/set-default-browser.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by dawholl** [comment]
@jeffdfield, Thanks for the feedback. Working on updates to take users looking for info about setting Edge as their default browser to this info: https://docs.microsoft.com/en-us/deployedge/edge-default-browser.

**Comment by dawholl** [comment]
@jeffdfield, to ensure that we're always providing users the most current information, the article in the Microsoft Search docs site has been removed and both the TOC link and the page URL now redirect users to this page in the Edge Enterprise docs site: [https://docs.microsoft.com/en-us/deployedge/edge-default-browser](https://docs.microsoft.com/en-us/deployedge/edge-default-browser).
