### ISSUE TITLE
Where can I see the user feedback for Bookmarks from bing enterprise?

### ISSUE THREAD

**Issue by christianb-7** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#123]
Hey guys,

i am looking for the location of the user-feedback for bookmarks that an user gives in bing to me.
![image](https://user-images.githubusercontent.com/77335934/104321020-5d074900-54e3-11eb-8810-476b0cb9ae8e.png)

The systems tells the user that an admin has been notified. What kind of admin is that and what role does he need?

regards Christian

**Comment by jeffkizn** [comment]
The form you are showing here is for the user to suggest a new bookmark. This suggestion is displayed to your organization's administrator. On the Bookmarks page of Microsoft Search admin center. It appears as a "Suggested" bookmark. Global Admin, Search Admin, and Search Editor can all [manage bookmarks](https://docs.microsoft.com/microsoftsearch/manage-bookmarks).
