### ISSUE TITLE
Global/Default Search Verticals List is Inaccurate

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#125]
### According to [this paragraph](https://docs.microsoft.com/en-us/microsoftsearch/customize-search-page#search-verticals-explained) in the indicated documentation, there are 5 organization-level default search verticals (see below):

1. All
2. People
3. Files
4. Sites
5. News

However, that does not appear to be the case.  The [SharePoint start page](https://sharepoint.com/) and [Office page](https://office.com/) search results include an additional default search vertical:  Power BI (see below).  

In addition, the[ Bing work search](https://bing.com/) results page shows another 2 additional search verticals:  Groups and Conversations (see below).  

This is relevant, because the 'All' search vertical does not include results from 3 additional verticals:  Power BI, Groups, and Conversations (see below).  Similarly, the 'All' search vertical also does not include results from any custom search verticals that are created/indexed.  

### I have opened a support ticket with Microsoft regarding this behavior (CR# 23540625).  

I was told that the 'All' search vertical will only include content from SharePoint and OneDrive.  If that is the case, I believe this behavior should be documented and perhaps the Microsoft Search team should consider renaming the 'All' vertical to something that will indicate it does not actually include 'All' search results.  

![image](https://user-images.githubusercontent.com/38665906/104776406-43f6d600-5737-11eb-9966-dbd04b2169f5.png)

![image](https://user-images.githubusercontent.com/38665906/104776331-23c71700-5737-11eb-8d5e-8c5d6ecc99ff.png)

![image](https://user-images.githubusercontent.com/38665906/104775678-f9288e80-5735-11eb-9ce9-055a240a3beb.png)

![image](https://user-images.githubusercontent.com/38665906/104776178-e6fb2000-5736-11eb-98df-c4398014c11c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-us/microsoftsearch/customize-search-page)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @jypal
* Microsoft Alias: **jeffkizn**

**Comment by AnjanaValsan** [comment]
Hello Tracy, thanks for the feedback. 
The list of verticals (tabs) on the search results page on Bing@Work and SP-Home + office.com are not the same. 
We are working towards coherence on both the endpoints. We will update the documentation to call out the 2 lists separately.

2) Our vision for the All vertical is to truly make it All. We have introduced the concept of result clusters on All vertical where snippets of connector results can show up, if there is a match. We would be improvising All vertical to bring in other content sources as well. Meanwhile, we are providing a feature to rename the default verticals. This feature will be available in Targeted Release channel starting early March.

Hope this helps. Do let me know for any further questions.

**Comment by TracyGH** [comment]
Thanks @AnjanaValsan!  Do you have a roadmap item for the feature to rename the default verticals?

**Comment by AnjanaValsan** [comment]
The feature to rename the default verticals is targeted for public preview in March. Please use the link here to track this feature release on our M365 roadmap.

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Search

The item id is 57054
