### ISSUE TITLE
Is it correct, that Search Administrator role is sufficient to access and manage search connectors? I have search admin role in our tenant, but I don't see the "Connectors" link in Search & Intelligence Admin Center.

### ISSUE THREAD

**Issue by bogdanskofek** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#126]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e785be0b-a0aa-13f2-21b9-2dd7defd39ea
* Version Independent ID: cba8efaa-5cdb-0c2d-db36-df4b740694c5
* Content: [Manage Microsoft Graph Connectors for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-connector)
* Content Source: [MicrosoftSearch/manage-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by jeffkizn** [comment]
Search admin is the role required. Connectors are generally available, but the controlled rollout goes first to customers that have opted into targeted release. If your admin account is part of Targeted Release, you should see Connectors in the admin center. If you have not opted into Targeted Release already, you can do that or you can wait for the rollout to continue to standard release customers.

[Connectors Overview](https://docs.microsoft.com/microsoftsearch/connectors-overview)

**Comment by bogdanskofek** [comment]
Thank you very much for the explanation!
