### ISSUE TITLE
Azure SQL indexing only works within same tenant

### ISSUE THREAD

**Issue by SteenW** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#127]
I tried to index an Azure SQL database using the instruction under "Register an app (for Azure SQL connector only)" - it works fine. However, if I try to do the same where the Connector is in tenant A and the Azure SQL database is located in tenant B it does not work. Please describe how this scenario is supported! 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Microsoft SQL server and Azure SQL connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @vivek
* Microsoft Alias: **vivg**

**Comment by mecampos** [comment]
Hello @SteenW, please note that the scenario you described, having the graph connector in tenant "A" and the Azure SQL database in tenant "B," is not supported.
