### ISSUE TITLE
Link to Modern Search?

### ISSUE THREAD

**Issue by frankok** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#128]
Why is there no link or reference to Microsoft Modern Search on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f13f-b678-3cb0-58e3-4e798201aa7a
* Version Independent ID: fe5470d4-8703-2ce3-7cf6-b53416f13199
* Content: [Get started with Microsoft Search in SharePoint Online](https://docs.microsoft.com/en-us/microsoftsearch/get-started-search-in-sharepoint-online)
* Content Source: [MicrosoftSearch/get-started-search-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-started-search-in-sharepoint-online.md)
* Service: **mssearch**
* GitHub Login: @tlarsen
* Microsoft Alias: **tlarsen**

**Comment by jeffkizn** [comment]
Thanks for your comment; can you please elaborate on it? The article talks able Microsoft Search and SharePoint classic search.

**Comment by frankok** [comment]
Thank you for your feedback, @jeffkizn. I didn't notice it was scoped to only classic search. Please ignore this then.
