### ISSUE TITLE
The link in step 2 is not working

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#13]
The link to the SharePoint Home page is only working for MS employees. Unless you want to open up the Microsoft intranet of course :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f13f-b678-3cb0-58e3-4e798201aa7a
* Version Independent ID: fe5470d4-8703-2ce3-7cf6-b53416f13199
* Content: [Get started with Microsoft Search in SharePoint Online](https://docs.microsoft.com/en-us/microsoftsearch/get-started-search-in-sharepoint-online#feedback)
* Content Source: [MicrosoftSearch/get-started-search-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-started-search-in-sharepoint-online.md)
* Service: **mssearch**
* GitHub Login: @tlarsen
* Microsoft Alias: **tlarsen**

**Comment by adefowler** [comment]
@bartvermeersch - Thank you! We've removed the broken link.
