### ISSUE TITLE
one search analytics for all ?

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#130]
so when user is searching from bing, or office.com or SharePoint home site, it will all be curated into one search report right ?

**Comment by jeffkizn** [comment]
Right now, we have Office.com and SPHome aggregated into these reports; Bing is coming very soon. So yes, these reports are intended to show all those surfaces. We also have [plans](https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=70616) to bring reports to Microsoft Search on SharePoint sites.
