### ISSUE TITLE
Connectors Purchase

### ISSUE THREAD

**Issue by AnnaRainbolt** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#131]
I waqleked thorugh teses steps and the Extra Graph Connector Capacity  was not listed ??

**Comment by mecampos** [comment]
Hello @AnnaRainbolt, to see information on how to purchase additional Graph connectors quota visit: 
License requirements and pricing 
https://docs.microsoft.com/en-us/microsoftsearch/licensing

**Comment by mecampos** [comment]
Closing as resolved.
Important to remember that it is necessary to select or "click" on Add-ons to see the full list of options.
