### ISSUE TITLE
We have no connectors configured and are getting a warning: "Your organization is out of space to index. You can purchase additional quota"

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#132]
> When index quota is exceeded for your organization, all active connections will be impacted, and those connections will operate in limit exceeded state. In this state, your active connections
> 
> Will not be able to add new items.
> 
> Will be able to update or delete existing items.
> 
> To fix this, you can do any of the following:
> 
> Learn how to purchase index quota for your organization at Licensing requirements and pricing.
> 
> Identify connections which have too much content being ingested and update them to index fewer items to make room for quota. To update the connection, you must delete and create a new connection with a new ingestion filter which brings in fewer items.
> 
> Permanently delete one or more connections

We have no connectors configured and are getting a warning: "Your organization is out of space to index. You can purchase additional quota"
Statistics below the warning show:
Total quota utilization (‎0‎%)
‎0‎ items indexed out of ‎0‎.

What are the instructions for managing this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e785be0b-a0aa-13f2-21b9-2dd7defd39ea
* Version Independent ID: cba8efaa-5cdb-0c2d-db36-df4b740694c5
* Content: [Manage Microsoft Graph Connectors for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-connector#monitor-your-index-quota-utilization)
* Content Source: [MicrosoftSearch/manage-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by MariaAngela24** [comment]
The message you received about your quota utilization and items indexed was sent accidentally. You can ignore the message. In order to ensure you receive correct information in the future, can you please send a link to this issue to MicrosoftGraphConnectorsFeedback@service.microsoft.com and include the following additional information:

1) The tenant ID where this happened
2) The exact location where you received the message. Please include a screenshot if possible.

Thanks very much for bringing this to our attention.

**Comment by angoo-atea** [comment]
Hi,

As requested…

Tenant ID: 5fa66c23-ecdc-4144-9a79-6a7a43073a18

Screenshot of location/error message:

[cid:image002.png@01D705CA.2DBF1870]





[cid:image003.jpg@01D705CA.8106ACF0]

Andrew Goodwin
Solution Architect

Direct: +46 46 16 33 27
andrew.goodwin@atea.se<mailto:andrew.goodwin@atea.se>
