### ISSUE TITLE
ServiceNow only showing "Everyone" in permissions step

### ISSUE THREAD

**Issue by spplante** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#133]
As documented [here](https://docs.microsoft.com/en-us/MicrosoftSearch/servicenow-connector#step-5-manage-search-permissions), the ServiceNow connector should offer two different options in the **Manage search permissions** step :

- Everyone
- Only people with access to this data source

However the only option I see is **Everyone**. The documentation also states the following :

```
The ServiceNow connector is in preview if you choose Only people with access to this data source.

```

Does that mean I have to enable preview functionalities somewhere in order to be able to see this option?!? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5175b51-8cee-6432-325e-216310e9ecb0
* Version Independent ID: a75c2239-2a07-e901-ac78-4dcde7bd197b
* Content: [ServiceNow Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/servicenow-connector)
* Content Source: [MicrosoftSearch/servicenow-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/servicenow-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @spplante , the "Only people with access to this data source" option is in preview for a limited group of clients at this point, and it will be open for a wider audience via targeted release in the next weeks. 
You can adopt it in your tenant if you opt-in for targeted release updates.

**Comment by spplante** [comment]
@mecampos  Yes I opened a ticket with Microsoft and they just confirmed me this. It would be useful to mention this in the documentation because currently it does say this option is in preview but nothing says it's still in development and not available even for targeted release tenants, it kinda is misleading as we speak :(

Thanks!

**Comment by mecampos** [comment]
Thank you very much for the feedback and suggestion @spplante.
