### ISSUE TITLE
ServiceNow Invalid redirect_uri Error

### ISSUE THREAD

**Issue by abates100** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#134]
We have been attempting to configure Microsoft Search connector for ServiceNow.  Connections using basic auth work fine.  After configuring the connection per these instructions https://docs.microsoft.com/en-us/microsoftsearch/servicenow-connector  using https://gcs.office.com/v1.0/admin/oauth/callback as the redirect  it pops open an empty window then fails  with the error 'Invalid redirect_uri.   What could be missing?  We have tested in multiple environments both using SSO and pre-logging into the instance but always the same error.

https://xxxxxxxxxxxxxxxxxxxxx.service-now.com/oauth_auth.do?client_id=e48axxxxxxxx839ac8945a&response_type=code&state=e3ff91d8-34c8-4b15-a0b4-18910a6ac575%257c52525252%257c7116&redirect_uri=https%3A%2F%2Fgcs.office.com%2Fv1.0%2Fadmin%2Foauth%2Fcallback

**Comment by mecampos** [comment]
Hello @abates100, please send a link to this issue to MicrosoftGraphConnectorsFeedback@service.microsoft.com, including the following information:

1. Tenant ID
2. Connection ID
3. Timestamp of the last occurrence of the problem.

If possible, please reproduce the problem one more time to get more recent logs.

**Comment by mecampos** [comment]
Closing this issue now, please note that it needs follow up using your account specific information via email with MicrosoftGraphConnectorsFeedback@service.microsoft.com
