### ISSUE TITLE
Access to quota for developers

### ISSUE THREAD

**Issue by SteenW** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#137]
After Feb 1st, the free quota for Graph connectors preview ended. As a MS DEV partner, how can we get access to a limited quota in order to develop and test our custom connectors without buying expensive E5/M5 license? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @SteenW, Microsoft is extending the free quota availability, and now it will expire on April 1st, 2021. You can continue using that option, or you can also explore a new type of license with Microsoft Viva Topics:

Microsoft Viva Topics
https://www.microsoft.com/microsoft-viva/topics?activetab=pivot:overviewtab

With Microsoft Viva Topics you have 2 possibilities:
1. Select the Free trial option.
2. Contact your Account Manager to request a promo code for trial index capacity to try out connectors. The promo code includes more topics and items than the Free trial.

Hope this helps!
Also please note that we are in the process of updating the document to add this information.
