### ISSUE TITLE
Guidance (Screenshots) for Creating Refiners on Custom Search Connectors/Verticals? 

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#138]
Piggy-backing off of [this issue](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/issues/113), I cannot find how to add refiners to my custom SQL search connector/vertical.  

According to the limitations listed in the [documentation](https://docs.microsoft.com/en-us/microsoftsearch/custom-filters):  "You can currently create filters only on string & date type managed properties."  But it's unclear what exactly is a managed property.  

Of the fields I'm pulling into my connector with the SQL query, only 1 is 'refinable' (see below), and that's the only one available to add as a filter in my associated vertical.  

There is a step in the connection wizard called Property Labels (see below).  I'm 'guessing' a subset of those are the only available (refinable) managed properties at this time.  And if that is the case, is it possible to retrieve the 'StringCollection' datatype listed for the Authors property label with a SQL query/source?  

![refinable](https://user-images.githubusercontent.com/38665906/109844963-e09f0580-7c09-11eb-94d4-ff4cb58ab841.png)
![propertylabels](https://user-images.githubusercontent.com/38665906/109844979-e563b980-7c09-11eb-8655-10e8982b53ba.png)

**Comment by maheshsinghania** [comment]
@TracyGH 
SQL connector maps varchar columns to data type string in search schema. There is no provision to map SQL columns to StringCollection in current SQL Connector.
Support for marking "string" attributes in search schema as "refinable" is planned in near future. Will keep you posted on this.

**Comment by rslavey** [comment]
@maheshsinghania Thank you. Please also consider int/bigint or other number refiners as well. This is a huge area for us as we like to refine values in a range (e.g. sales between $10,000 and $1,000,000, people with more than 20 clients, etc.)

Keep up the good work!

**Comment by maheshsinghania** [comment]
@rslavey - Yes, support for integer refiners for UDT connectors are also in the works. "People" vertical integer filters are not in immediate future though. Will keep you posted on the same.
Thank you.

**Comment by TracyGH** [comment]
@maheshsinghania - Any roadmap items for these?

1. Support for marking "string" attributes in search schema as "refinable"
2. support for integer refiners for UDT connectors

**Comment by maheshsinghania** [comment]
@TracyGH - yes both items are on roadmap.
1. Support for single valued string refiners is planned in next 2 quarters
2. Support for integer refiners for UDT connectors is planned for first half of calendar year 2022
