### ISSUE TITLE
Azure SQL Connector - Internal Server Error

### ISSUE THREAD

**Issue by JoeydeRijk7** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#139]
I am trying to setup MS Search using an Azure SQL Connector using the following guide: https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector. When I try to test the connection to the database, I am getting the following error: "There was an internal server error while processing the request."
![MSSearch1](https://user-images.githubusercontent.com/80055000/109988158-8e440e80-7d07-11eb-9fcb-197fc20925b3.png)

I made sure the correct IP's are allowed for the Azure database (I even tried the range 0.0.0.0 - 255.255.255.255).
The client ID and secret are correct for the app registration in AAD.
I used Fiddler to check if there was more info available but there isn't, except an call to the logclient containing the following data:
`[{
        "TagId": 504760,
        "LogLevel": 1,
        "Message": "GeneralException",
        "Adhoc0": "06a5f773-d06f-44ca-bd65-78b8c3a3f497",
        "Adhoc1": "657",
        "Adhoc2": "{\"data\":{\"ApiContext\":\"upsertAuthentication\",\"requestId\":\"893f91e9bc1ddf4f85104b4d3275798b\"}}"
    }, {
        "TagId": 500781,
        "LogLevel": 4,
        "Message": "UI Exception: GeneralException",
        "Adhoc0": "06a5f773-d06f-44ca-bd65-78b8c3a3f497",
        "Adhoc1": "657",
        "Adhoc2": "{\"version\":\"2021.2.18.4\",\"stack\":\"Error: GeneralException\\n    at Function.e.error (https://admin.microsoft.com/Adminportal/Home:298:90469)\\n    at F (https://prod.msocdn.com/M365/admin-main/2021.2.18.4/inline.en.7666.chunk.js:1:44845)\\n    at https://prod.msocdn.com/M365/admin-main/2021.2.18.4/inline.en.7666.chunk.js:1:43386\"}"
    }, {
        "TagId": 500298,
        "LogLevel": 1,
        "Message": "UI Analytics",
        "Adhoc0": "06a5f773-d06f-44ca-bd65-78b8c3a3f497",
        "Adhoc1": "658",
        "Adhoc2": "{\"data\":{\"location\":\"/MicrosoftSearch/Connectors/add\",\"hint\":\"ConnectorErrorBar\",\"value\":\"28cc3842-3b45-4a8e-b681-102160bed2cd|udt_0|auth failure\"}}"
    }
]`

Thats all the info I am getting. What else could I be missing that is not in the docs link above?

**Comment by mecampos** [comment]
Hello @JoeydeRijk7, please send a link to this issue to Microsoft Graph Connectors Feedback <MicrosoftGraphConnectorsFeedback@service.microsoft.com>, and include the following information:
1. The Tenant ID
2. Timestamp of the most recent occurence of the issue

**Comment by mecampos** [comment]
I'm closing this issue now, please note that in this case it is necessary to check the specific details of the tenant. Please continue to follow up via email with the Microsoft Graph Connectors Feedback group as suggested.
