### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#14]
The link to the "SharePoint home page" is only working for Microsoft employees.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df9ac41-dbce-9419-970f-1164834f6cce
* Version Independent ID: c4eae854-f518-b46d-18c8-d408f4f13dd4
* Content: [Microsoft Search Overview](https://docs.microsoft.com/en-us/microsoftsearch/overview-microsoft-search)
* Content Source: [MicrosoftSearch/overview-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/overview-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @tlarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
Thanks! I've removed the link.
