### ISSUE TITLE
Documentation on what is indexed in the Graph

### ISSUE THREAD

**Issue by rslavey** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#140]
Do you have a master list of what is indexed? I noticed I can search for schools in Delve, but from the Bing search, nothing comes up under people.

![image](https://user-images.githubusercontent.com/21177142/110187837-0299b300-7dd7-11eb-8090-d8d3e09755cf.png)

![image](https://user-images.githubusercontent.com/21177142/110187771-cb2b0680-7dd6-11eb-8003-2aa30097ce24.png)

**Comment by jeffkizn** [comment]
We are working on bringing these experiences to parity. Delve and Microsoft Search in Bing use the same underlying search technology, however, having come first, Delve also makes use of legacy search capability from SharePoint to backfill profile data like Education. Other Office clients like SharePoint and Office.com will have this experience as well. We are working on making Microsoft Search in Bing have the same capability to search on Education and deeper profile data.
