### ISSUE TITLE
talk about taking content down as well as putting it up

### ISSUE THREAD

**Issue by MrQuidd** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#141]
There is no mention of removing bookmarks - how long it takes to replicate etc etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0da86d-a561-e5d5-15ff-c0863de2a58b
* Version Independent ID: 66ecc43a-029f-70f7-62e9-3e7b77adc5d9
* Content: [Manage bookmarks](https://docs.microsoft.com/en-us/microsoftsearch/manage-bookmarks)
* Content Source: [MicrosoftSearch/manage-bookmarks.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-bookmarks.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by dawholl** [comment]
@MrQuidd, thanks for the feedback. Will try to add that info to the manage bookmarks topic in a few days. I'll leave a comment when it's been updated.

**Comment by dawholl** [comment]
@MrQuidd, added a Q&A to the FAQ section about removing deleted bookmarks from work results. If the page content has been cached, you may need to do a hard refresh to see the updated content.

**Comment by dawholl** [comment]
@MrQuidd, with the update to address your feedback now live I'm closing this issue.
