### ISSUE TITLE
Graph Quota - Index

### ISSUE THREAD

**Issue by Ninjaadamskis** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#142]
https://docs.microsoft.com/en-us/microsoftsearch/licensing

**Purchase of add-on index quota**
To purchase more Graph connectors quota get in touch with your Microsoft Account Manager, or complete the following steps:

It would be helpful if the Graph Quote was published as well. 
i.e.
How many items does the additional "Extra Graph Connector Capacity" provide? 
I know the current max is 7million. Does buying the Extra Graph Connector provide the max or do you buy multiple to get increments of 100k (etc.)? 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Thank you @Ninjaadamskis, note that the information you are requesting is visible in the Microsoft 365 admin center: https://admin.microsoft.com, when you follow the instructions provided in this article. Also as mentioned your Microsoft Account Manager can help you understanding the available options.
