### ISSUE TITLE
columns with "_" in their names are not supported

### ISSUE THREAD

**Issue by toskr** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#144]
It's worth mentioning, that column names can't have any non-alphanumeric characters in their names, e.g. the underscore "_"

(as far as I understand that limitation is imposed by Search, which is supposed to create crawled/managed properties based on column names, and "_" is not allowed in property names)

A lot of people have underscores in their column names in their databases.
And the error message we get when trying to use them is very confusing. It suggest the values in the columns are incorrect, and doesn't say the column name is the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Azure SQL and Microsoft SQL server Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Thank you very much for the feedback @toskr , we'll take it into account.
