### ISSUE TITLE
Support in GCC?

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#145]
Does Microsoft Search work in GCC tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af30bbd-1bc5-5026-87d9-8aa40de2489e
* Version Independent ID: ffb6b68d-57ff-270e-1b63-d7175a5b61d3
* Content: [FAQs](https://docs.microsoft.com/en-us/microsoftsearch/faqs)
* Content Source: [MicrosoftSearch/faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/faqs.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Microsoft Search is not available in GCC, GCC-H, or US DoD environments yet. We are working on this and will update the roadmap soon.
