### ISSUE TITLE
Need acceptable values for field "State"

### ISSUE THREAD

**Issue by wisc75** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#15]
You say the state field is required but you don't indicate what values are allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e72062-8f29-4762-390e-61c746a0ae70
* Version Independent ID: a03281f8-9804-ea11-fe1d-bf1938600a9c
* Content: [Bulk create locations](https://docs.microsoft.com/en-us/microsoftsearch/bulk-create-locations?redirectSourcePath=%252fen-us%252farticle%252fbulk-create-locations-15c9fada-f7a6-4210-aa6b-028b32217830#feedback)
* Content Source: [MicrosoftSearch/bulk-create-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/bulk-create-locations.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by prabita** [comment]
@wisc75 - Hi, thank you for your feedback. Please see the updated content available at:
https://docs.microsoft.com/en-us/microsoftsearch/manage-locations
