### ISSUE TITLE
API's Available For Insights Data?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#155]
Is the Search and Intelligence > Insights data available via the MS Graph API?  And if not, is there a roadmap item to indicate when it will be added?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37967c2e-89bc-9a30-062f-5ced811e9c46
* Version Independent ID: 0f4f3219-9b95-2dfb-8de3-9daaf8447766
* Content: [Search Usage Reports](https://docs.microsoft.com/en-us/microsoftsearch/usage-reports)
* Content Source: [MicrosoftSearch/usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/usage-reports.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **ankmis**

**Comment by jeffkizn** [comment]
Search usage data is not available via API. It is an item that is under investigation but nothing concrete to add to the roadmap yet.
