### ISSUE TITLE
Crawl wiki pages

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#157]
Does this Azure DevOps connector also crawl wiki pages? We use a combination of SharePoint for documents and Azure DevOps wiki for wiki based workflows. It makes sense to have a single search results experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc3089d0-b049-f945-4fc2-48d0077269a2
* Version Independent ID: 15e31305-b630-6cd4-1e4f-ac6b2adf61c8
* Content: [Azure DevOps Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/azure-devops-connector)
* Content Source: [MicrosoftSearch/azure-devops-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/azure-devops-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @cveld, please note that the Azure DevOps connector does not index wiki pages, it only indexes work items. The functionality to index wikis is under development. A preview of the functionality might be available by the end of June. 
If you are interested in previewing the functionality, you can send an email to MicrosoftGraphConnectorsFeedback@service.microsoft.com, referencing this issue and including your tenant ID.
