### ISSUE TITLE
Need clarity on which steps apply

### ISSUE THREAD

**Issue by jmcmike** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#159]
[Enter feedback here]
The instructions seem like they need some clarification.  For step 3, connection settings, in the 3rd option, (Azure AD OIDC) it says the following steps apply.  But which steps?  Just step 3a-f?  All of the steps, in which case step 4-9 do NOT apply to service now authentication?  This may be clear to some, but I am really having a hard time wrapping my head around which steps apply to what.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5175b51-8cee-6432-325e-216310e9ecb0
* Version Independent ID: a75c2239-2a07-e901-ac78-4dcde7bd197b
* Content: [ServiceNow Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/servicenow-connector)
* Content Source: [MicrosoftSearch/servicenow-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/servicenow-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @jmcmike , please note that I did not find an specific line on this article saying "the following steps apply", I'll appreciate if you can confirm the specific section that you are pointing out in this case.
For a better understanding of the setup process, and the steps involved you can first read the "Setup overview for Graph connectors by Microsoft" document here: https://docs.microsoft.com/en-us/microsoftsearch/configure-connector.
