### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#16]
When I go to the Microsoft Search in Bing page, it shows me that Microsoft Search in Bing is now availalble, but there is not a Location tab to click on . HOw can I get this fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96809b75-c20f-bfcf-9a69-7793f51172bf
* Version Independent ID: 48f803b7-3759-f040-895f-45e1b6559768
* Content: [Make content easy to find with Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/make-content-easy-to-find#location)
* Content Source: [MicrosoftSearch/make-content-easy-to-find.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/make-content-easy-to-find.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by WendyStidmon** [comment]
Hi Dean,

I think we got your fixed now, correct? If not, please follow-up up with me in the Search Forum on Tech Comm.

Cheers,
-Wendy
