### ISSUE TITLE
Floorplan search question / feedback

### ISSUE THREAD

**Issue by kingad** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#161]
When adding floorplans to Microsoft search - who are the results visible to?  Are the floorplans available to the world, or somehow only limited to domain users?
Where would I learn more about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e310a1cf-f2d0-0613-51ae-2fb6646ac4e1
* Version Independent ID: fae06982-6bfa-2cc7-8507-18fa721f5972
* Content: [Manage floor plans](https://docs.microsoft.com/en-us/microsoftsearch/manage-floorplans?WT.mc_id=365AdminCSH_support?WT.mc_id=365AdminCSH_globalsearch)
* Content Source: [MicrosoftSearch/manage-floorplans.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-floorplans.md)
* Service: **mssearch**
* GitHub Login: @rasrivas
* Microsoft Alias: **rasrivas**

**Comment by jeffkizn** [comment]
@kingad Like other results from Microsoft Search, floor plan answers will be available to your organization only.

**Comment by kingad** [comment]
Thanks Jeff.

I also found some of the basics of Microsoft search and I’m reading more about that to educate myself.

Andy

Andrew King
Manager, Software Systems
CDM Smith
Suite 400, 503 Martindale Street, Pittsburgh, PA 15212
Pronouns: He, him, his
[LinkedIN]<https://www.linkedin.com/in/king-andrew-9aa58a8a/>
cdmsmith.com<http://www.cdmsmith.com/>
[http://www.cdmsmith.com/-/media/Images/CDMSmith_logo_302x180.png]<https://www.cdmsmith.com/>
[http://www.cdmsmith.com/-/media/Icons/Social-Icons/facebook-icon-gray.png]<https://www.facebook.com/CDMSmith/>
[http://www.cdmsmith.com/-/media/Icons/Social-Icons/twitter-icon-gray.png]<https://twitter.com/CDMSmith>
[http://www.cdmsmith.com/-/media/Icons/Social-Icons/instagram-icon-gray.png]<https://www.instagram.com/cdmsmith/?hl=en>
[http://www.cdmsmith.com/-/media/Icons/Social-Icons/linkedin-icon-gray.png]<https://www.linkedin.com/company/cdmsmith/>
[http://www.cdmsmith.com/-/media/Icons/Social-Icons/youtube-icon-gray.png]<https://www.youtube.com/user/CDMSmith>
