### ISSUE TITLE
Isn't this setting "enabled" by default? 

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#162]
Isn't this setting "enabled" by default? 

https://docs.microsoft.com/en-us/microsoftsearch/result-cluster#enable-result-clusters
-------------------------------
Enable result clusters
The result cluster experience is turned off by default.

Follow these steps to turn on the experience at the organization level:

In the Microsoft 365 admin center, go to Verticals.
Select the All vertical, then enable Show connector results.
-------------------------------

https://lynx.office.net/messagecenter/MC253495 commented This is on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c18e36-9714-5e35-de06-2a252e743cbd
* Version Independent ID: 6548815c-be43-a8f6-4fa8-ef0a059cc109
* Content: [Connectors result cluster](https://docs.microsoft.com/en-us/microsoftsearch/result-cluster?source=docs)
* Content Source: [MicrosoftSearch/result-cluster.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/result-cluster.md)
* Service: **mssearch**
* GitHub Login: @Manusi
* Microsoft Alias: **manusi**

**Comment by manusi18** [comment]
Hi,

Thanks for your query.

The default Admin option for showing Connector Results in "All" tab for MSO and MSB is presently disabled. We will be changing the default option to "ON" by early next month and the same is communicated through the MC post.

If you would like to see the Connector results in "All" tab before that, you may enable this option via the Admin panel using the instructions shared here: https://docs.microsoft.com/en-us/microsoftsearch/result-cluster#enable-result-clusters 

Thanks.

**Comment by o365tatsuyan** [comment]
Thank you for your prompt reply. Now, I got it.  But if so, it would be grateful if you can change this article to the default option "on" by early next month, too.　
FYI.. currently, this enable/disable option seems to be not working even I change this option thru the above metioned Admin panel, thought..　

kind regards,

**Comment by manusi18** [comment]
Thank you. We are working on the change and we will update here as soon as the default option is changed to "ON".

However, with the manual option change, the Connector results should show in All tab in MSO and MSB (with other conditions being met), could you please share your issue to this email id: MicrosoftGraphConnectorsFeedback@service.microsoft.com so we can help and take a look. 

Thanks.

**Comment by manusi18** [comment]
We will be closing this issue as the resolution was shared over email. Please feel free to reach out to us at MicrosoftGraphConnectorsFeedback@service.microsoft.com for any queries.  Thanks.
