### ISSUE TITLE
Login failed for user '<token-identified principal>' when trying to connect to serverless Azure SQL

### ISSUE THREAD

**Issue by ekdegerman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#165]
I've been following these instructions to try to configure the Azure SQL connector for a serverless Azure SQL DB created for testing purposes. However, I keep getting the error above even after creating the app registration as a user in the database and assigning the db_datareader role. Can you confirm if this should work? They are both in the same tenant, as I saw another issue mention that different tenants are not supported (which would also be good to mention in the text to avoid wasted time). From some parts of the documentation for Azure SQL I get the impression that app registrations may only work with managed instances, but it is rather vague so I'm not sure if I am reading that right...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Azure SQL and Microsoft SQL server Graph connector for Microsoft Search](https://docs.microsoft.com/en-US/microsoftsearch/mssql-connector)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @ekdegerman, thank your for bringing this to our attention. Please send a link to this issue to MicrosoftGraphConnectorsFeedback@service.microsoft.com and include the tenant ID where this happened.

**Comment by mecampos** [comment]
Hi @ekdegerman, no problem, you can follow up via the same email with our Engineers, and they will help you addressing both issues.
