### ISSUE TITLE
Amazon S3 Partner Description Appears Wrong

### ISSUE THREAD

**Issue by justnchew** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#169]
In the [Connectors Gallery ](https://docs.microsoft.com/en-us/MicrosoftSearch/connectors-gallery), it looks like the description for the Amazon S3 Provider is wrong. The description lists:

> Connector for Adobe AEM. Indexes pages, attachments, and other generated document types from Adobe AEM in near real time. The connector fully supports AEM's built-in user and group management, as well as AEM installations based on Active Directory and other directory services. Sixth generation Raytion search connector.

However the Title is Amazon S3 By Accenture, and not Raytion.

**Comment by mecampos** [comment]
Thank you for bringing this to our attention @justnchew, I'll update the description accordingly.
