### ISSUE TITLE
Missing Menu Item

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#17]
When I log into a new demo tenant, when I go to Microsoft 365 admin center, I cannot select Microsoft Search under Settings in the left navigation panel because it does not exist. How can I get this to show up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df67176-e302-f972-dbf7-d7e0747e5bd2
* Version Independent ID: e213129d-0fb1-31ee-a654-091d032c2746
* Content: [Set up **Microsoft Search**](https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search)
* Content Source: [MicrosoftSearch/setup-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/setup-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by adefowler** [comment]
@DeanGross - Are you viewing the admin center in "Preview mode"?

**Comment by DeanGross** [comment]
yes, i was. It turned out that this was a bug that has been fixed by MSFT, the documentation is correct.
