### ISSUE TITLE
Linguistics not supported for the Microsoft SQL Server connector?

### ISSUE THREAD

**Issue by ekdegerman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#170]
I have been running some tests with the Microsoft SQL Server connector to index a couple of on-prem databases. When testing the result, it behaves quite different from the regular SharePoint search when it comes to linguistics. Normally when searching for team I would get a hit for items containing e.g. teams as well, but this is not the case for my SQL connector content. This is not listed on the page as a limitation, though. Can you confirm if linguistics should already work so that it is my configuration that is incorrect? Or if not, will it at some point work for these connectors just like it does for SharePoint content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Azure SQL and Microsoft SQL server Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @ekdegerman, it will be good to have a closer look at the issue you found, please send an email to MicrosoftGraphConnectorsFeedback@service.microsoft.com with this information, and include the ‘tenant ID’ and connector ‘connection ID’ that you are using for these tests. You can also send the link to this GitHub issue for reference.

**Comment by ekdegerman** [comment]
@mecampos Sent! Sorry about the delay.
