### ISSUE TITLE
Empty Data Source field while editing Result Types

### ISSUE THREAD

**Issue by shridha21** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#171]
Version used 4.1

While trying to Edit Result Types the "Data source Field" Drop down is blank 

![EmptyDataSourceField](https://user-images.githubusercontent.com/46351822/121446417-73fe7a00-c961-11eb-8469-fbffbf93add9.png)

**Comment by wobba** [comment]
Issues for PnP Modern Search should be logged at https://github.com/microsoft-search/pnp-modern-search/issues
