### ISSUE TITLE
Purchasing graph connector quota is no longer offered like described here (at least for us)

### ISSUE THREAD

**Issue by BerndGewehr** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#172]
[Enter feedback here]
Purchase of add-on index quota
To purchase more Graph connectors quota get in touch with your Microsoft Account Manager, or complete the following steps:

In the Microsoft 365 admin center: https://admin.microsoft.com navigation menu, go to Billing > Purchase services.
At the bottom of the Purchase services page, select Add-ons.
Select Extra Graph Connector Capacity.
Select Buy then complete your order preferences.
Select Check out now.

I can not find that product in my offerings on that purchasing page. How to buy? Need 60+million items for a large file share...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-US/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @BerndGewehr, thank you reaching out , please contact your Microsoft Account Manager as soon as possible to to help you in this case.

**Comment by BerndGewehr** [comment]
Hi Melissa,

I have found that you need to have some preconditions met to see that offering on your purchase services page. This article made me think it should always be there but you need to have either E5 licenses with included msgraph search capacity or another service like the viva topics trial that has it. As soon as you have one of those, you see the offering. A hint would be nice to help others find that condition faster than me.

BTW: It seems to be far too expensive to be used for our 60 Mio files on the network file shares so we stopped this initiative.

All the best!

Bernd Gewehr

**Comment by mecampos** [comment]
Thank you for your feedback @BerndGewehr, and for letting us know that you were able to find the information you needed, I will make the E5 licenses requirement more clear on the second paragraph of the article. Best!
