### ISSUE TITLE
You refer to the concept of a result cluster on this page, but never defined it nor do you provide a picture of a UI implementing one.

### ISSUE THREAD

**Issue by dwightkruger** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#173]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c18e36-9714-5e35-de06-2a252e743cbd
* Version Independent ID: 6548815c-be43-a8f6-4fa8-ef0a059cc109
* Content: [Connectors result cluster](https://docs.microsoft.com/en-us/microsoftsearch/result-cluster)
* Content Source: [MicrosoftSearch/result-cluster.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/result-cluster.md)
* Service: **mssearch**
* GitHub Login: @Manusi
* Microsoft Alias: **manusi**

**Comment by manusi18** [comment]
Hi,

I didn't quite understand the issue here.  

Connectors Result Clusters helps to show relevant connector results in the "All" tab in MSO and MSB (Work vertical). The experience can be enabled through the Admin panel with the steps mentioned in the documentation page.  

Can you please explain the issue you are facing. Thanks.

**Comment by maheshsinghania** [comment]
Hi,
Please find below a description of the Result Cluster usage. This will soon be updated on the docs too. 
Do let us know if you have any questions.

Follow these steps to turn on the experience at the organization level:
1.	In the Microsoft 365 admin center, go to Verticals in Search and Intelligence Customizations.
2.	Select All vertical and click the More Options ellipses symbol to toggle "Show connector results".
  
![image](https://user-images.githubusercontent.com/72018014/126669937-7a5688df-4b0c-4ffe-84be-655226381add.png)

After enabling the Show connector results option, if there is a highly relevant result in the custom vertical for the query, the result cluster is displayed on the All page as follows.
 
![image](https://user-images.githubusercontent.com/72018014/126670125-172d6e89-ecf1-4b99-b3a9-e1acf53b1c21.png)


Follow these steps to turn on the experience at the SharePoint site level:
1.	On the SharePoint site where you want the result cluster experience, go to Settings.
2.	Go to Site information>View all site settings.
3.	Go to the Microsoft Search section, then select Configure Microsoft Search for this site collection.
4.	In the navigation pane, go to Custom experience, then select Verticals.
5.	Select and double click the All vertical to enable Show connector results toggle.
 
![image](https://user-images.githubusercontent.com/72018014/126670254-e759d15d-086a-4f2b-a250-06131f5b4d08.png)

**Comment by jeffkizn** [comment]
The documentation has been updated with a graphic and additional details.
