### ISSUE TITLE
Is there a way to display search results from my custom Graph connector under the "All" Vertical?

### ISSUE THREAD

**Issue by VelinGeorgiev** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#178]
Hi, Is there a way to display results from my custom Graph connector under the "All" Vertical? I have indexed data that shows correctly under my custom Vertical, but does not appear under the "All" vertical.  Not having my custom connector data displayed under the "All" vertical makes any custom connector almost useless. 
![image](https://user-images.githubusercontent.com/1049476/125318219-2fcc1400-e329-11eb-8c75-05610eb995b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e785be0b-a0aa-13f2-21b9-2dd7defd39ea
* Version Independent ID: cba8efaa-5cdb-0c2d-db36-df4b740694c5
* Content: [Manage Microsoft Graph Connectors for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-connector)
* Content Source: [MicrosoftSearch/manage-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **mecampos**

**Comment by monaray97** [comment]
Hi @VelinGeorgiev, you can enable a result cluster for your connector which will show a set of connector results under "All." See this page here for more information: https://docs.microsoft.com/en-us/microsoftsearch/result-cluster. Let me know if you have any other questions.

**Comment by VelinGeorgiev** [comment]
Thanks for your response @monaray97!

However, the article you pasted did not help.

![image](https://user-images.githubusercontent.com/1049476/126364798-8a96542a-11d7-43ea-aad1-1dc38896ae51.png)

Here is what I did (according to the article)
- Opened my Microsoft Search Admin panel
- Navigated to the Verticals
- Selected "All" and set it to "Show Connector Results"
- Waited 24 hours.
- Tested with my custom connector data, but results did not appear under the "All" Vertical while testing/searching.
![image](https://user-images.githubusercontent.com/1049476/126365065-b4d74030-cf91-490b-a300-5a87e67c68cd.png)

Looks like custom Graph Connectors do not appear under the "All" Vertical making the Graph Connectors something that is not mature and usable at the moment. It is just not worth the configuration and development effort to create a connector that does not display data under the "All" Vertical.

**Comment by VelinGeorgiev** [comment]
@jthake-msft not sure if you can help, but I am desperately seeking for at least yes, no answer here.

**Comment by jypal6** [comment]
Hi @VelinGeorgiev , can you validate if the "title" and the "content" are set up correctly for your custom connector. Discovery of the content is dependent upon this. Excerpt from the article "Relevant results are chosen based on the "title" property and "content" property of each item. The content property is marked as isContent=true on the schema." 

Your custom connector schema should have "title" label added to the correct properties for discoverability. Some reference articles: 
https://docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&tabs=http 
https://docs.microsoft.com/en-us/microsoftsearch/configure-connector#step-5-assign-property-labels 
https://docs.microsoft.com/en-us/microsoftsearch/configure-connector#content-property

Hope this helps

**Comment by maheshsinghania** [comment]
Hi @VelinGeorgiev 
To add to @jypal6 comment, Result cluster will display results from custom verticals on All page with a high relevance threshold. While there might be matching results in custom verticals, if they fall below the relevance cutoff they will not be displayed on Result Cluster in All page. 
Mapping title and other semantic labels to the connector properties can lead to better relevance.
If you are unable to get desired results, please do share your connection schema to look at.
Thanks.

**Comment by jypal6** [comment]
Hi @VelinGeorgiev 
Were the above pointers helpful. Do let us know if the results are now showing under the All vertical.
