### ISSUE TITLE
Acronym needs to be one word

### ISSUE THREAD

**Issue by bipinprakashtss** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#179]
[Enter feedback here]
The acronym section does not perform a validity check if the acronym has more than one word. It allows multiple words to be treated as a valid acronym but does not show up in search results. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd51764-80a7-b404-50bd-b492b193dab2
* Version Independent ID: 62a6858b-81a3-bafa-4bcc-3bb2a951c654
* Content: [Manage Acronym answers in Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms)
* Content Source: [MicrosoftSearch/manage-acronyms.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-acronyms.md)
* Service: **mssearch**
* GitHub Login: @RakeshMSFT
* Microsoft Alias: **rakkum**

**Comment by RakeshMSFT** [comment]
@bipinprakashtss Thank you for sharing your valuable feedback with us. To understand further, kindly help with some more inputs. Could you please mention which acronym section you are referring to. Also, sharing an example of the concern with the expected outcome with us might be helpful here. Thank you.

**Comment by bipinprakashtss** [comment]
Hi Rakesh,

Sure thing. So, from under the search and intelligence admin center, under answers and then acronyms, if you were to make an entry for an acronym that is not just one word, so pretty much anything with a blank space E.g. Student center for example would not work. It would have to be studentcenter as one word or something else. This makes sense by definition but there is no form validation to detect for a blank space and warn the user that they have entered an unacceptable acronym. It took support/engineering close to 6 weeks before coming to a resolution on my case but I think a simple field/form validation would have helped warn me of the error.

Thanks,
Bipin
________________________________

**Comment by RakeshMSFT** [comment]
@bipinprakashtss Thank you for adding more details. It's a valid point that there could be explicit instructions on the form while adding the Acronym. We have acknowledged this and will work on the admin portal page to add the supporting instructions. Thanks again for sharing your valuable feedback with us.

**Comment by bipinprakashtss** [comment]
Hi,

Also, the fact that an incorrectly  formatted acronym is accepted and shows up in the list of all acronyms makes it challenging to think that there is a bad acronym.

Best,
Bipin

**Comment by RakeshMSFT** [comment]
@bipinprakashtss Valid point.
