### ISSUE TITLE
Content settings not available for Norway

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#18]
I cannot find the Content Settings described under Step 3. Is this available for customers in Norway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cfd814-0551-a1c9-1001-0bdf2a028c6b
* Version Independent ID: d6ee9a96-33f1-0dcb-5bb7-f5695a3a1987
* Content: [Quick set up for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/quick-set-up#step-3-customize-content-settings)
* Content Source: [MicrosoftSearch/quick-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/quick-set-up.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by prabita** [comment]
Hi, thank you for your feedback. Please see the updated content available at:
https://docs.microsoft.com/en-us/microsoftsearch/

**Comment by rajeshkhanikar** [comment]
The link posted by you loads a marketing page about search. Don’t see any changes to the original article. Is this Content Setting page available for customers in Norway? I still don’t see it. The article is misleading.

**Comment by adefowler** [comment]
Sorry for the confusion, but that is the landing page for support content on docs.microsoft.com. That's where we keep all of our ITPro and Admin help content. 

https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search <-- Here's the direct link to the new set up content. We moved the Microsoft Search in Bing portal to the Microsoft 365 admin center and the content is completely different. Again, sorry for any confusion.
