### ISSUE TITLE
Cannot create connector

### ISSUE THREAD

**Issue by mocher72** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#186]
I am trying to follow the tutorial linked here

https://docs.microsoft.com/en-us/microsoftsearch/configure-connector#step-1-add-a-graph-connector-in-the-microsoft-365-admin-center

And when I try to create a new connection I get an error when trying to create the name ‘The request is malformed or incorrect’
example in the attached screenshot.

![connactorfail](https://user-images.githubusercontent.com/40542735/127783666-025e7961-f232-4946-b720-17c67ab0c485.png)

I am using a dev account which allows up to 12500 items to be indexed.

**Comment by MariaAngela24** [comment]
I see this question has also been sent to the microsoftgraphconnectorsfeedback@service.microsoft.com email alias. We will provide technical support via that forum.
