### ISSUE TITLE
Registering Microsoft Graph Connector Agent Fails

### ISSUE THREAD

**Issue by Preeti1910** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#190]
I am trying to setup Microsoft Graph connectors for network file share

I created a demo tenant.
Login in azure portal with my demo tenant credentials.
Registered an app and grant permission as per this document https://docs.microsoft.com/en-us/microsoftsearch/on-prem-agent

After this I installed GCA from  https://aka.ms/GCAdownload, then login in GCA using my demo tenant credential. Now when I am trying to register GCA with AppId and client secret of the App registered in above step, I am getting error
![image](https://user-images.githubusercontent.com/13446409/128333260-8d6e834a-e461-4105-9e5d-8dc185f003af.png)

I am not getting where I am wrong. will appreciate any help.

**Comment by TheKarthikeyan** [comment]
Hello @Preeti1910  ,

Could you please share your tenant id and issue details over mail to MicrosoftGraphConnectorsFeedback@service.Microsoft.com
Our engineering team will be able to assist you.

Thanks.

**Comment by Preeti1910** [comment]
Hi All,

The issue is resolved now. Thank you

**Comment by mecampos** [comment]
Thank you for letting us know @Preeti1910, I'll close this issue now.
