### ISSUE TITLE
What is an "instance".

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#192]
There's no information on this page or in the M365 admin page for purchasing "Extra Graph Connector Capacity" regarding exactly what an "instance" is.

_Billing frequency options
‎SEK 8,737.00‎ ‎**instance‎**/month
Pay monthly, annual commitment_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by TheKarthikeyan** [comment]
Hello @angoo-atea,

Instance means an M365 tenant. Thank you for the feedback. We will make the communication clearer on the billings page.
