### ISSUE TITLE
Microsoft Search content creator browser extension cannot be found in Edge extensions

### ISSUE THREAD

**Issue by ZasGanto** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#193]
[Enter feedback here]
On this page a link and mention to an Edge extension is made for easily adding bookmarks. The link is dead and I can not find the extension anywhere through the Extensions menu in my Edge settings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0da86d-a561-e5d5-15ff-c0863de2a58b
* Version Independent ID: 66ecc43a-029f-70f7-62e9-3e7b77adc5d9
* Content: [Manage bookmarks](https://docs.microsoft.com/en-us/microsoftsearch/manage-bookmarks?WT.mc_id=365AdminCSH_SupportCentral)
* Content Source: [MicrosoftSearch/manage-bookmarks.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-bookmarks.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by dawholl** [comment]
@ZasGanto, link to the legacy Edge extension has been removed. Chromium Edge and Chrome users can install the content creator extension from the Chrome Web Store. Thanks for your comment!
