### ISSUE TITLE
Cannot create connector

### ISSUE THREAD

**Issue by mocher72** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#194]
As the Microsoft support microsoftgraphconnectorsfeedback@service.microsoft.com email alias cannot support a site in the DEU German domain then I will reopen this here.

I am trying to follow the tutorial linked here

https://docs.microsoft.com/en-us/microsoftsearch/configure-connector#step-1-add-a-graph-connector-in-the-microsoft-365-admin-center

And when I try to create a new connection I get an error when trying to create the name ‘The request is malformed or incorrect’
example in the attached screenshot.

![connactorfail](https://user-images.githubusercontent.com/40542735/129277091-75d6387f-d48c-4db7-841b-5cf49e6416ad.png)

I am using a dev account which allows up to 12500 items to be indexed.

**Comment by rsamai** [comment]
Adding @anonymous085 to help create this File Share connector

**Comment by rsamai** [comment]
This issue is being followed on the Graph connectors feedback alias. Meet Gupta is tracking it
