### ISSUE TITLE
Error while testing connection in ADLS Gen2‎' Connector

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#196]
HI team,

I am trying to create an Azure data lake gen 2 graph connector to crawl.
When entering the primary connection of the Azure storage account its giving me connection error.

![image](https://user-images.githubusercontent.com/54174168/129357717-e143dc0a-76b2-429f-b58d-736aee1047c7.png)
Can someone help??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50de042c-12a6-c58f-9fe5-a0bce5fcad2f
* Version Independent ID: 5959d47b-754f-c0f8-5606-f4e39884d013
* Content: [Azure Data Lake Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/azure-data-lake-connector)
* Content Source: [MicrosoftSearch/azure-data-lake-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/azure-data-lake-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by rsamai** [comment]
Adding @suhel82  to help with this ADLS connector testing error

**Comment by anonymous085** [comment]
@bvats Since Suhel is OOF

**Comment by mecampos** [comment]
Hello @lovyjain, please let me know if you still need assistance with this issue? Thanks

**Comment by mecampos** [comment]
Hi @lovyjain, I'm going to close this issue now, please note that you can re-open it if you need further assistance.
