### ISSUE TITLE
What is the expected launch date for Dynamics 365 federation search

### ISSUE THREAD

**Issue by sobrienns** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#197]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3986f11-1c91-cbda-5acb-12896bc70a92
* Version Independent ID: ea4a6997-0f71-3a83-7702-0f54252e84f3
* Content: [Dynamics 365 federation search (preview)](https://docs.microsoft.com/en-us/microsoftsearch/manage-dynamics365)
* Content Source: [MicrosoftSearch/manage-dynamics365.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-dynamics365.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by rsamai** [comment]
@CindyLiu-D365 from Dynamics 365 to help answer this question

**Comment by dawholl** [comment]
@sobrienns, article has been updated with a link to the Microsoft Search roadmap, which includes release date information. Closing this issue with this comment.
