### ISSUE TITLE
Add links to relevant documenation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#2]
please add links to help us get started on these idea, e.g., integrating PowerApps sound cool, but i'm not really sure what is meant by this. Providing links to articles about the various examples would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb71344-2497-490c-8670-d5e9b6b3421b
* Version Independent ID: 1e01ad06-e508-44ef-43a2-c60d969d89fa
* Content: [Why Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/why-microsoft-search)
* Content Source: [MicrosoftSearch/why-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/why-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by prabita** [comment]
@DeanGross Thank you for your feedback. Please see the PowerApps section in Manage Bookmarks page:
