### ISSUE TITLE
Use the authorization code to request an access token on the redirect URL webpage

### ISSUE THREAD

**Issue by jonathaneckman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#202]
In the Authentication section, it is unclear where I'm supposed to go for this step:

> To get the values for the resource, client_id, and client_secret, go to Use the authorization code to request an access token on the redirect URL webpage.

I dont see the resource id, a "Use the authorization code to request an access token" page or link, and I'm not sure what you mean by the redirect URL webpage. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9c66b8-91aa-0eb5-60d3-d33efb7efea0
* Version Independent ID: 2371960d-b4d6-ba49-15c9-50f2aa9f341a
* Content: [Enterprise websites Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/enterprise-web-connector)
* Content Source: [MicrosoftSearch/enterprise-web-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/enterprise-web-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Thank you for bringing this up @jonathaneckman , I am going to review the document to validate the steps.

**Comment by judyhnguyen** [comment]
Hi @mecampos, any update here?

**Comment by mecampos** [comment]
Hi @jonathaneckman Please send an email to: MicrosoftGraphConnectorsFeedback@service.microsoft.com , including your tenant id and issue details. Our Engineering team should be able to review the cause of the error in this case and provide a recommendation.
I'll continue to review the article to determine if an update is needed as well.
