### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by SamMataDMM** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#206]
Feedback capitalized in subheading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3cb1796-ba59-ba0c-f99e-cb88bdb8e28c
* Version Independent ID: bdbdb631-15c0-a207-0efb-2289ff76de20
* Content: [Managing User Feedback](https://docs.microsoft.com/en-us/microsoftsearch/manage-feedback)
* Content Source: [MicrosoftSearch/manage-feedback.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-feedback.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **lebhansa**

**Comment by jeffkizn** [comment]
Thanks for catching it; we've fixed it. Next time you can use the "edit" button on the page and make the correction yourself. We always appreciate the help! :)

**Comment by SamMataDMM** [comment]
NP, wasn't sure if I had the privileges to do it. But will do next time!
