### ISSUE TITLE
ServiceNow connector crawling error 5000 "Something went wrong"

### ISSUE THREAD

**Issue by tjkb** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#208]
I've setup a ServiceNow connector like this:
**Properties**
![image](https://user-images.githubusercontent.com/40162050/141121523-a047f9ae-eeed-46c0-a7a7-fc7b02e7767b.png)

**Permissions**
![image](https://user-images.githubusercontent.com/40162050/141121642-1544ee9a-6cf1-4340-ba4f-4427e9f24a91.png)

**Properties**
![image](https://user-images.githubusercontent.com/40162050/141121672-ce82dca9-ca98-4b76-b696-8fc25a1cb443.png)

**Labels**
![image](https://user-images.githubusercontent.com/40162050/141121765-3346dc6c-16e0-41f5-bb23-107e7d47d7f7.png)

Please note: 

1. In the properties screenshot you can see that the preview shows data, so there is no permission problem with the accounts involved
2. In the labels screenshot, contrary to many tutorials, I'm unable to assign any properties to a label. All it says is _Not applicable_

When a full crawl is running, all I get are errors for each item that it should add to the index:
![image](https://user-images.githubusercontent.com/40162050/141122356-063efc62-9627-461d-b5b0-c24c700688ba.png)
Error 5000, with a detailed error code 3104.

What am I doing wrong?

**Comment by TheKarthikeyan** [comment]
@tjkb we have fixed a known issue that caused this error. Can you please try creating a new connection to verify whether it works?

Thanks,
Karthikeyan
