### ISSUE TITLE
select "Configure Microsoft Search for this site collection" is not availbale in first release tenancies

### ISSUE THREAD

**Issue by mikedockray** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#209]
Even in a first release tenancy the option to "Look for the Microsoft Search section, and then select "Configure Microsoft Search for this site collection" is not availbale.   Does this need to be turned on somewhere or is it yet to be rolled-out ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c1b924-ef47-230c-ea15-648cd525b850
* Version Independent ID: 1761c8f2-9a84-52c4-27a2-4fce1cba62d6
* Content: [Manage  filters](https://docs.microsoft.com/en-us/microsoftsearch/custom-filters)
* Content Source: [MicrosoftSearch/custom-filters.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/custom-filters.md)
* Service: **mssearch**
* GitHub Login: @Revathi-b
* Microsoft Alias: **v-revathib**

**Comment by maheshsinghania** [comment]
Hi Mike, by first release do you mean your tenant is on TR (Targeted release)? 

If yes, can you share your tenant ID with searchcustomization@microsoft.com to check. It should be available for tenants which have opted into TR.

If no, please wait for the public release.

thanks,
Mahesh

**Comment by mikedockray** [comment]
Mahesh,

Thanks for responding so quickly. Yes I am on "targeted release for everyone"

My Tenant ID is : 90efcce1-7b40-4980-9489-878bfe32fcb6

[cid:9eb36c05-2dc4-41bc-b85c-e3b5a754c89e]

[cid:edb660f6-5013-42cb-8b0d-a3feb7450a4c]


Am i looking in the wrong place ?

Thanks,
Mike



[breadcrumb digital]<http://breadcrumbdigital.com.au/>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au



________________________________

**Comment by mikedockray** [comment]
[breadcrumb digital]<http://breadcrumbdigital.com.au/>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au



________________________________

**Comment by mikedockray** [comment]
Adding +Kratika, current week's OCE for AdminUX issues.
________________________________
From: Mike Dockray ***@***.***>
Sent: Monday, November 22, 2021 11:49 AM
To: Search Customization Issues ***@***.***>
Cc: MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-MicrosoftSearch] select "Configure Microsoft Search for this site collection" is not availbale in first release tenancies (Issue #209)




[breadcrumb digital]<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fbreadcrumbdigital.com.au%2F&data=04%7C01%7Cgauravchugh%40microsoft.com%7Cdfe08744b91e45c7f4f308d9ad801e80%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637731588542777816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BU5SnfUIwy2IDvcMkijeTluZcLCAx2iCG7dwLQ2rIFU%3D&reserved=0>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au



________________________________

**Comment by jeffkizn** [comment]
I believe the team was delayed in rolling out this feature. We will revert the documentation update.

**Comment by jeffkizn** [comment]
That looks like a doc error in navigation. 

@mikedockray are you just looking for how to find the Microsoft Search admin page in SharePoint? If so:
1. In the SharePoint site where you want to manage verticals, open the settings panel by clicking the gear.
2. Select Site information, and then select View all site settings. 
3. Look for the Microsoft Search section, and then select Configure search settings.

Or are you looking for a specific feature of Filters?

**Comment by mikedockray** [comment]
Jeff,

Thanks for that info. 'Evergreen' has caught me out again... i did not notice that the 'Microsoft Search' was now on Site Settings for individual site collections.

Verticals and Result types are there indeed.

[cid:b4cfe3fe-4c80-44f5-bdce-4485318e7d39]


>Or are you looking for a specific feature of Filters?

Is there something else I missed about Filters ?

I appreciate your feedback, thanks very much.

Mike



[breadcrumb digital]<http://breadcrumbdigital.com.au/>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au



________________________________

**Comment by mikedockray** [comment]
Jeff,

I am a SharePoint Admin who has been customising search since SharePoint 2010 on-premise and every version since then, i do know Search. However, SPO Modern search had none of the customisation of classic search.

Functionality is now being taken over by Microsoft Search. I understand the need for Data Sources in Microsoft Search to pull data in from third party systems but why does it not let you add SharePoint Data Sources ?

Now you have shown me the Microsoft Search in a Site Collection I can add a vertical and point it to a SharePoint Content Source , add KQL Queries and filters :

[cid:f284ac18-2603-4237-a4d6-c180e9fc54d3]



However when trying to do same on a Site Collection Result type you are unable to choose SharePoint as Content Source ?   Is this functionality coming on Roadmap ?

[cid:76ec319a-7269-4e55-b938-0f232d2c91dd]

Thanks,
Mike



[breadcrumb digital]<http://breadcrumbdigital.com.au/>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au


________________________________

**Comment by maheshsinghania** [comment]
+ @Jyoti ***@***.***> to comment on the plans for result type customization on SharePoint content.

Hi Mike – yes it is in the roadmap. Jyoti can update on the latest.

Regards,
Mahesh

**Comment by maheshsinghania** [comment]
Hi Mike – I am assuming that you are unblocked on configuration of verticals on the site collection. Please let us know if you have queries on that.
On the SharePoint customization we will update on the roadmap plan.

Thanks,
Mahesh

From: Mahesh Singhania
Sent: 23 November 2021 09:24
To: MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; Jyoti Pal ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-MicrosoftSearch] select "Configure Microsoft Search for this site collection" is not availbale in first release tenancies (Issue #209)

+ @Jyoti ***@***.***> to comment on the plans for result type customization on SharePoint content.

Hi Mike – yes it is in the roadmap. Jyoti can update on the latest.

Regards,
Mahesh

**Comment by maheshsinghania** [comment]
Hi,

The following roadmap id can be used to track the work item : https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=81952

Note: The ship timeline is expected to be change from Dec 2021 to first half of 2022. The exact timeline will be updated soon.



Best Regards,

Jyoti Pal
she/her
SENIOR PROGRAM MANAGER
[Microsoft Logo]

________________________________
From: Mahesh Singhania ***@***.***>
Sent: Tuesday, November 23, 2021 14:45
To: MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; Jyoti Pal ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-MicrosoftSearch] select "Configure Microsoft Search for this site collection" is not availbale in first release tenancies (Issue #209)


Hi Mike – I am assuming that you are unblocked on configuration of verticals on the site collection. Please let us know if you have queries on that.

On the SharePoint customization we will update on the roadmap plan.



Thanks,

Mahesh



From: Mahesh Singhania
Sent: 23 November 2021 09:24
To: MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; MicrosoftDocs/OfficeDocs-MicrosoftSearch ***@***.***>; Jyoti Pal ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-MicrosoftSearch] select "Configure Microsoft Search for this site collection" is not availbale in first release tenancies (Issue #209)



+ @Jyoti ***@***.***> to comment on the plans for result type customization on SharePoint content.



Hi Mike – yes it is in the roadmap. Jyoti can update on the latest.



Regards,

Mahesh

**Comment by mikedockray** [comment]
Thanks very much for all of your help. much appreciated


[breadcrumb digital]<http://breadcrumbdigital.com.au/>

Mike Dockray
SharePoint Specialist
0404 313 828
breadcrumbdigital.com.au



________________________________
