### ISSUE TITLE
How to add to SharePoint Online Modern Sites

### ISSUE THREAD

**Issue by nledger** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#212]
How can I add the Microsoft Search in your intranet to a SharePoint Online Modern Sites intranet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a214bc03-7c17-dd30-d989-c528d3e3aa44
* Version Independent ID: 40e0be7b-afc9-232b-48d6-c3a98f19a78c
* Content: [Add a search box to your intranet site](https://docs.microsoft.com/en-us/microsoftsearch/add-a-search-box-to-your-intranet-site)
* Content Source: [MicrosoftSearch/add-a-search-box-to-your-intranet-site.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/add-a-search-box-to-your-intranet-site.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by jeffkizn** [comment]
@nledger If you have a modern SharePoint site with the search box in the header, that site is already running Microsoft Search. This article is for older, SharePoint classic sites or 3rd party sites/pages.
