### ISSUE TITLE
Update link to Set-PnPPage

### ISSUE THREAD

**Issue by coreyroth** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#214]
[Enter feedback here]
Under "Change the layout of your custom results page", the link to the PowerShell cmdlet should now be Set-PnPPage.  It's currently a 404 when you click on the link.
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnppage?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6155388f-afc0-e18a-c039-9ae20214e342
* Version Independent ID: 74a3dc05-1312-fa5f-9e6c-bf5dcbdd35e9
* Content: [Create a custom search results page in SharePoint Online](https://docs.microsoft.com/en-us/microsoftsearch/create-search-results-pages)
* Content Source: [MicrosoftSearch/create-search-results-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/create-search-results-pages.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Thanks for the update. This is now fixed.
