### ISSUE TITLE
Instructions are incorrect

### ISSUE THREAD

**Issue by angusmaul** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#215]
After creating the data source for salesforce, the  result type is not created automatically

These instructions are incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 791f603e-9d26-9ebe-b621-ac83f3bab184
* Version Independent ID: 24d3a18f-a048-ff91-3a98-adbbd3400fae
* Content: [Salesforce Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/salesforce-connector)
* Content Source: [MicrosoftSearch/salesforce-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/salesforce-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @angusmaul, thank you for bringing this to our attention, I'll start a review of this article.

**Comment by mecampos** [comment]
Hello @angusmaul , please note that I reviewed the article and confirmed the steps are correct.
According to Step "9: Review connection", the result type will be registered, but the result layout depends on the fields selected in Step 3.

You can follow the steps again, and if you get the same result send an email to: MicrosoftGraphConnectorsFeedback@service.microsoft.com, including the following additional information:

1. The tenant ID where this happened
1. Screenshots showing that the result type was not created.

Best,
