### ISSUE TITLE
Could we have Win10 and ProPlus requirements to this page?

### ISSUE THREAD

**Issue by markuspelto** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#22]
Would it be possible to have system requirements for Windows Search? What Windows (10) build version is required and what ProPlus build version is required? Also are there some other consideration in the device side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df67176-e302-f972-dbf7-d7e0747e5bd2
* Version Independent ID: e213129d-0fb1-31ee-a654-091d032c2746
* Content: [Set up **Microsoft Search**](https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search#feedback)
* Content Source: [MicrosoftSearch/setup-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/setup-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by adefowler** [comment]
Thank you for taking the time to comment. I'd like to follow up on your question...Windows Search and Microsoft Search are two different products. Are you asking about how those two products work together? Or do you want information on Windows Search? Here's a link to Windows Search documentation: https://docs.microsoft.com/en-us/windows/win32/search/windows-search Let me know if this answers your question or if you have more. Thank you!
