### ISSUE TITLE
Connectors no longer called Connectors 

### ISSUE THREAD

**Issue by asumner** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#220]
Connectors no longer called Connectors in the Tabs but are now named Data Sources.
Documentation and images are now out of date and first timers waste a lot of time due to the mismatch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7603d084-916d-dd63-b458-cfea25ba113f
* Version Independent ID: e1b3b948-37be-7cd2-38d7-7f18e67ce291
* Content: [Connectors Details and Errors](https://docs.microsoft.com/en-us/microsoftsearch/connector-details-errors)
* Content Source: [MicrosoftSearch/connector-details-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/connector-details-errors.md)
* Service: **mssearch**
* GitHub Login: @monaray97
* Microsoft Alias: **monaray**

**Comment by judyhnguyen** [comment]
Hi @mecampos, please let me know if you need more context on this ask to update the documentation.
