### ISSUE TITLE
Microsoft Search- Acronym automation

### ISSUE THREAD

**Issue by prteotia** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#221]
Hi Team,

is there a way to automate acronym addition and publishing in microsoft search.
Scenario is like there is a set of acronym that can be added to search but before adding , it should go for approval and approved acronym can be added and published. 

I want to **automate** this, say by using PowerShell or power automate. If there is any way , please let me know.

Thanks,
Preeti

**Comment by jeffkizn** [comment]
We have APIs for administration on the horizon. The roadmap item is slightly out of date. Instead of Dec. 2021 it should read Q1CY22. Once the API is available you will be able to use that for your scenarios.
