### ISSUE TITLE
Change of API permission on atlassian => which permission to select instead?

### ISSUE THREAD

**Issue by Bvanderstraeten** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#222]
Api of confluence just change today apparently. which permission are required now?

Those didn't work
![image](https://user-images.githubusercontent.com/66592413/150992737-301d5954-b11b-47e0-8c54-09dc12905cb1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ede08aa-7a5b-9566-1372-32f533c3cda3
* Version Independent ID: 674e409b-7ce6-3366-c559-0fd63bd41c59
* Content: [Confluence Cloud Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/confluence-cloud-connector)
* Content Source: [MicrosoftSearch/confluence-cloud-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/confluence-cloud-connector.md)
* Service: **mssearch**
* GitHub Login: @TheKarthikeyan
* Microsoft Alias: **kam1**

**Comment by TheKarthikeyan** [comment]
@Bvanderstraeten In which version of Confluence you are seeing this?

**Comment by Bvanderstraeten** [comment]
On confluence cloud. I follow the documentation on saturday but it was not working, and this monday, on the développer app of atlassian, it state that the old api were deprecated and that I need to change permission and that the call back URL had to be changed

Regard
________________________________

**Comment by TheKarthikeyan** [comment]
@Bvanderstraeten could you please share the link to the API deprecation announcement? 
Thanks,

**Comment by Bvanderstraeten** [comment]
I didn't find any annoncement. Today it roll back to another interface in the permission  of atlassian, probably a glitch or an upcoming change.
Still didn't work (but work well for Jira)

**Comment by TheKarthikeyan** [comment]
Please contact Atlassian support for help.
