### ISSUE TITLE
Contradiction in claims

### ISSUE THREAD

**Issue by dyost17** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#223]
The claim:

"Users get results that are relevant in the context of the app they search from." (and subsequent text)

directly contradicts the claim made two bullets later:

"Users don't need to remember where the information is located." (and subsequent text)

This is a major shortcoming of Microsoft 365 that I'm currently dealing with, where a search will not search across the entire ecosystem, so I do, in fact, have to remember which "app" or "product" it was in. Was it Word? A comment my colleague made in Planner or Teams? An email? I don't know, but I know that thing-I-need was somewhere in our M365 universe and I just want to search, but search doesn't search all applications. So yes, I do in fact have to know where the information is located, which almost entirely defeats the purpose of searching.

It is true that contextualization and relevance still play key roles, absolutely, and search results could be ordered and presented in a way to help preserve that value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21c56af-67d4-48df-370a-545d9e92d0e7
* Version Independent ID: a83b1eb0-1361-066a-bbe4-3f7ef4a219e0
* Content: [Microsoft Search Overview](https://docs.microsoft.com/en-us/microsoftsearch/overview-microsoft-search)
* Content Source: [MicrosoftSearch/overview-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/overview-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Thank you for calling this out. This document has been updated, removing the contradiction.
