### ISSUE TITLE
Three types of "search contents" in brief?

### ISSUE THREAD

**Issue by Urbs3w** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#225]
I find Microsoft Search interesting as a potential part of one or more conceptual approaches to taking legacy network file shares and changing to/moving to something for my users.  **I am wondering, and perhaps others, too, in just a few words, or very briefly and concretely, what are the three types of "search contents"?** I was expecting to see three clear types,  it's not 100% clear to me what they are:

> In Microsoft Search, administrators have three different search contents that they can create for a better search experience and to improve the "findability" of content.

> Bookmarks are the most commonly used answer type. They promote the best possible results for your users’ queries to the top of the search results and make it easy for your users to find what they are looking for. Informational content that is available for everyone; for example, information about the company, help for Windows and Office apps, etc. Content that people in the organization generally search for in their day-to-day work. Common work-related searches include employee benefits, time and expense reporting, submitting purchase orders, and getting help from IT services. For creating and managing answers, see [Plan your content](https://docs.microsoft.com/en-us/microsoftsearch/plan-your-content).

I thought I'd see more about the three types of search contents in [Plan your content](https://docs.microsoft.com/en-us/microsoftsearch/plan-your-content), but I didn't seem to.  The three types of search contents sounds sort like an abstract concept. Maybe it'd make more sense if I were able to dig into the actual Microsoft Search settings in an M365 tenant,  but I don't have that ability.

PS:

Thank you for the documentation. I always appreciate the depth and breadth of MS documentation

In this case, the Microsoft Search materials are helpful for my research I mentioned earlier into tackling network file shares. 

Though my place has a lot in the Enterprise EDMS and much in SharePoint, my department/branch still has a significant amount of files in network file shares. We have multiple file servers, but on the most used one, the Windows Search (the indexer) just can't handle either the size of the data or the number of items (I forget which) in a single index... I am thinking that maybe as a temporary workaround, the files on that one FS could be split up and spread out across multiple file servers so that the index on each wouldn't get overwhelmed... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df67176-e302-f972-dbf7-d7e0747e5bd2
* Version Independent ID: e213129d-0fb1-31ee-a654-091d032c2746
* Content: [Set up Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search)
* Content Source: [MicrosoftSearch/setup-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/setup-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
@Urbs3w, thank you for the comments and the callout on unclear documentation. This statement appears to come from a very early release of Microsoft Search which contained only three Answer types (Bookmarks, Q&As and Locations). We will get this document updated to make more sense.

**Comment by jeffkizn** [comment]
Content has been updated.

**Comment by Urbs3w** [comment]
Thank you fir the explanation and the modification to the doc. And thank you for the tip on the file share graph connector.
