### ISSUE TITLE
Update Graph Connector Agent Connection Details

### ISSUE THREAD

**Issue by Jiannko** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#226]
I had successfully configured the Graph connector Agent and set a DataSource (from Search and intelligence page ) with the Agent to search data from File share.
. But now as my client secret has expired , I am looking for ways to update  
it in the below dialogue. 
So that the existing DataSource that is already configured with the Agent works again .(Its in a failed status currently)

![image](https://user-images.githubusercontent.com/30264405/152156772-1e607d02-6269-44fd-a0f6-9db1a19a97fb.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4953fce7-a71e-1d25-723e-52d902246aff
* Version Independent ID: e1cf30fa-1009-fa93-0d2e-d0536f56b784
* Content: [On-Premises Agent](https://docs.microsoft.com/en-us/microsoftsearch/graph-connector-agent)
* Content Source: [MicrosoftSearch/graph-connector-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/graph-connector-agent.md)
* Service: **mssearch**
* GitHub Login: @rsamai
* Microsoft Alias: **rusamai**

**Comment by rchanda1392** [comment]
For now, we recommend downloading the latest version of the agent and reinstalling the same. We'll be releasing a new version soon which would allow users to edit/update their credentials directly from the app. We're engaging with the customer over email for this.
