### ISSUE TITLE
It seems not to include Embed documents in OneNote

### ISSUE THREAD

**Issue by mrsbeata** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#23]
I have an issue where we want to export e-mails to OneNote and documents automatically e-mail attachements become embeded documents. These documents can't be serched as is from Office 365.

I have problems with our recommendations since it's not easy for the end users to know how to act now in these GDPR times and every piece of information is a personal info. Even e-mail addresses and names.

My first issue is to be able to search it.

**Comment by adefowler** [comment]
Thank you so much for taking the time to comment. Yes, you are correct that files embedded in OneNote don't get indexed and therefore, can't be searched. If you want to "work around" this, the solution is to copy/paste content into OneNote instead of embedding the files with "Send to OneNote".

**Comment by mrsbeata** [comment]
Ok, that sux since my users (12 000) need to do this for all emails they need to save and you can’t set that to default. It costs a few more clicks and you can’t export multipel e-mails that way.

**Comment by adefowler** [comment]
So, this is feedback for the content writers (which I have forwarded to the product group). If you'd like to give feedback directly to them, you can go to our Customer voice website and submit it as a request. And then you can get other to vote for it. https://office365.uservoice.com/forums/273493-office-365-admin <-- When you're done, come back here and leave a comment with the URL to your request and I'll make sure the product group gets it.

**Comment by mrsbeata** [comment]
Hi,

Why would I leave an issue for OneNote in the Uservoice for Office 365 admin? 

I did however weeks ago find this issue, voted for, spread around my Customer and asked for them to vote for it as Well. 

https://onenote.uservoice.com/forums/327186-onenote-for-windows/suggestions/16318531-enable-search-for-text-in-embedded-documents-or-at

Please do send it on to the Product group, this is an issue which is making our GDPR group wanting to shut down the project since we then might hide personal information in a place where we can’t even Search for it. 

I am stuck between a rock and GDPR and really need help. Why doesn’t Search include it? 

And another side note to my troubles, print to PDF from email doesn’t seem to be in a searchable format either which makes no sense What so ever.

**Comment by adefowler** [comment]
Mostly because you are an admin and OneNote is an office product and this is more about administration. So, to me it made sense (I'm an admin writer). I've forwarded your feedback and all else to the Microsoft Search product group. And I've also updated the documentation to include the information about OneNote and embedded docs. And I've sent a note also to the Outlook team about the PDF issue. Thanks again for taking the time to provide feedback! It's people like you that help us make great products. :-)

**Comment by mrsbeata** [comment]
Ok, that is great and all. But it would also be awesome to get some feedback from the Search procut Group. I'm not just here to help you with this, you are also here to help me so that I can help the users. I am still in the exact same position as Before with no real prognosis of even being able to give them anything.
