### ISSUE TITLE
Cost to use Microsoft Search with Office 365 E3?

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#232]
It's unclear if there is a cost to Microsoft Search for Office 365 E3 licenses.  Please update to clarify.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c08284-65dd-376f-b48c-1203f536da6b
* Version Independent ID: 8b85dbb2-5656-60e1-8baa-567472d8c8d8
* Content: [License requirements and pricing](https://docs.microsoft.com/en-us/microsoftsearch/licensing)
* Content Source: [MicrosoftSearch/licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/licensing.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by jeffkizn** [comment]
Microsoft Search is included with all Office 365 licenses. Microsoft Search will index all your 1st party content if Office 365 and surface that data through search in the O365 apps. This article is specifically for the use of Graph Connectors which are used to ingest 3rd party data to the Microsoft Search index. These connectors are used to bring in data from other clouds and sources. When using these connectors, you must ensure you have sufficient index quota to store the data being ingested. Each E5 license includes 500 items of index quota for Graph Connector data . E3 licenses do not include any index quota. You can purchase a quota add-on to get capacity for Graph Connector data if you only have E3 licenses.
