### ISSUE TITLE
Cost?

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#233]
Is there any cost to use Microsoft Search for Office 365 customers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af30bbd-1bc5-5026-87d9-8aa40de2489e
* Version Independent ID: ffb6b68d-57ff-270e-1b63-d7175a5b61d3
* Content: [FAQs](https://docs.microsoft.com/en-us/microsoftsearch/faqs)
* Content Source: [MicrosoftSearch/faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/faqs.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Microsoft Search is a part of Office 365; there is no additional cost to use it.

**Comment by GitWesDone** [comment]
Could this be added to the FAQ?

**Comment by jeffkizn** [comment]
Note in FAQ has been added.
