### ISSUE TITLE
translation issue for Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#236]
Hello, community

There are some incorrect translations. One of them has the opposite meaning, so could you please correct them?

article for Japanese
https://docs.microsoft.com/ja-jp/microsoftsearch/configure-connector?source=docs

### **1. At the beginning of the article**

![image](https://user-images.githubusercontent.com/13634805/158296413-95727469-8f20-4ff3-98f8-5fea3cbc9060.png)

- Orijinal
This article shows the basic process required to set up the Graph connectors by Microsoft in the Microsoft 365 admin center. The basic process includes the following steps:

- Actual
この記事では、Microsoft によるコネクタのセットアップにGraph基本的なプロセスを示Microsoft 365 管理センター。 基本的なプロセスには、以下のステップが含まれます。

- Suggestion
この記事では、Microsoft 365 管理センターにおける Microsoft が提供するコネクタの基本的なセットアップ プロセスを示します。基本的なプロセスには、以下のステップが含まれます。

### **2. Note of "Restrictions and recommendations for search schema settings" section**

![image](https://user-images.githubusercontent.com/13634805/158296470-4156db1f-2fd9-43bd-a52d-9bb563488793.png)

- Orijinal
Note

After you create a connection, you can't modify the schema. To do that, you need to delete your connection and create a new one.

- Actual
注意

接続を作成した後は 、スキーマを 変更**できます**。 これを行うには、接続を削除して新しい接続を作成する必要があります。

(* Opposit meaning)

- Suggestion
注意

接続を作成した後は、スキーマを変更**できません**。これを行うには、接続を削除して新しい接続を作成する必要があります。

### **3. "Step 8: Refresh settings" section**
![image](https://user-images.githubusercontent.com/13634805/158298526-67ab7b30-cd5a-4ade-83e6-57d7e24cb87a.png)

- Original
The refresh interval determines how often your data is synced between the data source and Microsoft Search.

- Actual
更新間隔は、データ ソースとデータ ソースの間でデータを同期する頻度Microsoft Search。

- Suggestion
更新間隔は、Microsoft Search とデータ ソースとの間でデータを同期する頻度を決定します。 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8979c8b-d009-2611-c803-61353f4aae0a
* Version Independent ID: eff84f91-933e-b3e7-875b-29acbf837e46
* Content: [Configure your Microsoft-built Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/configure-connector?source=docs)
* Content Source: [MicrosoftSearch/configure-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/configure-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by cdowling1971** [comment]
Hi @kefujino this issue is now logged with our translation service team and a fix will be implemented asap. Thanks for reporting this issue.
FYI @mecampos

**Comment by mecampos** [comment]
@kefujino, thanks again for reporting this problem , I am closing this issue now, and we will continue to follow up internally.
