### ISSUE TITLE
I don't want to use MS Search with Bing, stop showing it to me

### ISSUE THREAD

**Issue by conorforgey** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#24]
So, whenever I search something in Bing, the "sign in to see work results" bar pops up. Every time this happens, I select "Hide This -> Always", and it will invariably show up again in the same session, within an hour at most. I'm not interested in using the product, why even bother telling me I can hide it when it still shows up _in the same session_. 

Who do I have to mention to give some semblance of support towards this, because I'm legitimately tired of seeing it every time I search something. I'm pretty sure I've attempted to hide it at least 95% of the time, and nothing's changed in the last two weeks of this.

**Comment by adefowler** [comment]
Thank you for taking the time to provide feedback! Please clear your cache/cookies from all the browsers you are using reboot your machine. This should resolve your issues.
