### ISSUE TITLE
Update required for Step 3a: Full crawl (Required).

### ISSUE THREAD

**Issue by ravisundar13** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#241]
Please mention "**When using soft Delete it is mandatory to restrict the query results using soft delete condition**". The screen shot shows the query but not part of the documentation. This took us bit long time to understand why the soft delete items appearing after full Crawl. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Azure SQL and Microsoft SQL Server Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector?msclkid=35e2a66aa9ae11ec91cda5f756c388ff)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @ravisundar13, thank you for your feedback.
Could you please provide more details about the options that you are referring in the user interface?
In the article, as part of Step 3a we mentioned the following "To exclude soft-deleted rows in your database from being indexed, specify the soft-delete column name and value that indicates the row is deleted.": https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector?source=docs#skipping-soft-deleted-rows-optional 
Best,

**Comment by mecampos** [comment]
Hello @ravisundar13, I'll be closing this issue now, please review my previous comment and feel free to re-open it if further assistance is required.
