### ISSUE TITLE
Root folder is not reachable FileShare DataSource

### ISSUE THREAD

**Issue by mraf2022** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#243]
Hi there
When i try to connect on-prem file share datasource, i get error root folder is not accessible. Can you please update documentation to indicate how this can be diagnosed or resolved.

**Comment by Arvind-Ravi** [comment]
@msharshkum - Tagging you here.

**Comment by msharshkum** [comment]
> Hi there When i try to connect on-prem file share datasource, i get error root folder is not accessible. Can you please update documentation to indicate how this can be diagnosed or resolved.

Hi @mraf2022 , Can you please provide more details on what is your setup and what error you seeing (screenshots would help). You can reach out to us thru email: MicrosoftGraphConnectorsFeedback@service.microsoft.com

**Comment by jmslau** [comment]
@mraf2022, I am closing this issue. Please reach out to the above email address if you are still experiencing issue.
