### ISSUE TITLE
Link of Learn about item insights is missing

### ISSUE THREAD

**Issue by mohammadamer** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#245]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21c56af-67d4-48df-370a-545d9e92d0e7
* Version Independent ID: a83b1eb0-1361-066a-bbe4-3f7ef4a219e0
* Content: [Microsoft Search Overview](https://docs.microsoft.com/en-us/microsoftsearch/overview-microsoft-search)
* Content Source: [MicrosoftSearch/overview-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/overview-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Thanks for catching that. We have added the link.
