### ISSUE TITLE
Create an app:  Step 7 needs to be updated

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#249]
Create an app

Step 7 needs to be updated

7. Search for "ExternalItem.ReadWrite.All", "Directory.Read.All" and "ExternalItem.ReadWrite.OwnedBy" from the permissions and select Add permissions.

In above step "ExternalItem.ReadWrite.OwnedBy" needs to be replaced with "ExternalConnection.ReadWrite.OwnedBy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4953fce7-a71e-1d25-723e-52d902246aff
* Version Independent ID: e1cf30fa-1009-fa93-0d2e-d0536f56b784
* Content: [Graph Connector Agent](https://docs.microsoft.com/en-us/microsoftsearch/graph-connector-agent)
* Content Source: [MicrosoftSearch/graph-connector-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/graph-connector-agent.md)
* Service: **mssearch**
* GitHub Login: @rsamai
* Microsoft Alias: **rusamai**

**Comment by judyhnguyen** [comment]
@rchanda1392 Hi Rajdeep, I believe you own the Graph Connector Agent. Can you update the documentation or work with one of the content teams to correct step 7 please? 

Thank you!
Judy

**Comment by msharshkum** [comment]
Fixed the issue
