### ISSUE TITLE
Changes in Verticals are not reflected in Bing

### ISSUE THREAD

**Issue by vw-pro** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#251]
Hi,

I'm trying to understand the functioning of the verticals and it's impact in Bing Search. Any change I do on Verticals, is not reflecting in the bing search, even after I add "&features=uncachedVerticals", it is not clearing the cache for the verticals. It takes long time to see the effect of those changes. Is there a way, I can see these changes faster?

**Comment by jypal6** [comment]
Hi, 

There are two parts to your question and I want to make sure I understand correctly. 

1. From the second part of the question it looks like the changes done to the vertical are visible in Bing Search. Can you please confirm this? I would like to know if there are cases where changes do not reflect at all. 
2. You would like to have shorter time for changes to reflect in Bing Search. Can you share the amount of time it took for the changes to reflect despite using "&features=uncachedVerticals"

**Comment by jypal6** [comment]
Hi @vw-pro ,

We have taken this as a feedback and are tracking this in our backlog. At present , "&features=uncachedVerticals", is the way to clear cache and view changes made. Closing this as there is no further response from original poster. 

Best Regards,
Jyoti Pal

**Comment by vw-pro** [comment]
It took more than a day to see the changes in Bing even after adding &features=uncachedVerticals in the url.
