### ISSUE TITLE
Automatically  published Bookmarks will not return in a search from SharePoint.

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#260]
According to the product group, bookmarks must be manually published ("editorial")  to show in SharePoint searches. Auto-published ("mined") bookmarks for SharePoint sites will show in Bing work search, but not SharePoint search. (IcM at https://portal.microsofticm.com/imp/v3/incidents/details/294631573/home.) 

This should be added to the section "Publish or review recommended bookmarks" but I'm not sure how to word it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0da86d-a561-e5d5-15ff-c0863de2a58b
* Version Independent ID: 66ecc43a-029f-70f7-62e9-3e7b77adc5d9
* Content: [Manage bookmarks](https://docs.microsoft.com/en-us/microsoftsearch/manage-bookmarks#publish-or-review-recommended-bookmarks)
* Content Source: [MicrosoftSearch/manage-bookmarks.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-bookmarks.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by dawholl** [comment]
@fselkirk added note about availability of both manually and autopublished recommended bookmarks to the bookmarks docs article, [Manage bookmarks | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftsearch/manage-bookmarks). You may need to do a hard refresh to see the updated content. Also updated the ICM with the same info. Closing this issue with this comment.

**Comment by fselkirk** [comment]
Thank you Dawn! The note was clear, and I was able to send a link to the improved documentation to the customer when closing his case. This addition will prevent a lot of frustration in the future, as more customers begin using these features.

Frances Selkirk
Sr. Support Escalation Engineer
SharePoint and OneDrive Technical Support
+1 (857) 453-6233
Working Hours: M-Th, 9:30-6:00 ET  (Friday hours limited)

Need help outside of my working hours?
Manager: Priyanka Mendiratta, ***@***.******@***.***>
