### ISSUE TITLE
allow OOB Result layout ?

### ISSUE THREAD

**Issue by annigam01** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#263]
Is their option to change OOB "Result layout" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed997b94-55a7-1a7f-ff29-869039a91ce4
* Version Independent ID: e95ff5ad-2872-7269-7b8d-ed3221b806cf
* Content: [Manage search result layouts](https://docs.microsoft.com/en-us/microsoftsearch/customize-results-layout)
* Content Source: [MicrosoftSearch/customize-results-layout.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-results-layout.md)
* Service: **mssearch**
* GitHub Login: @jypal6
* Microsoft Alias: **jypal**

**Comment by jypal6** [comment]
Hi @annigam01, Can you please share more details on this. Which OOB result layout are you referring to? Would this be files, sites etc?

**Comment by jypal6** [comment]
Closing this as the topic was covered in https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/issues/262
