### ISSUE TITLE
Search usage reports article feedback

### ISSUE THREAD

**Issue by alexouretski** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#269]
This article is missing information about admin roles required to access these reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37967c2e-89bc-9a30-062f-5ced811e9c46
* Version Independent ID: 0f4f3219-9b95-2dfb-8de3-9daaf8447766
* Content: [Search Usage Reports](https://docs.microsoft.com/en-us/microsoftsearch/usage-reports)
* Content Source: [MicrosoftSearch/usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/usage-reports.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **ankmis**

**Comment by jeffkizn** [comment]
The [Setup article](https://docs.microsoft.com/microsoftsearch/setup-microsoft-search) details the Search Admin and Search Editor roles. Both roles have access to the usage reports page.
