### ISSUE TITLE
Search Verticals in GCC

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#272]
This article should call out that this capability is not available in all instance of Microsoft Search.  For example it is not available in GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d6641c-0b6e-fecd-5037-f4ccc2547865
* Version Independent ID: 3f7384e4-1941-23ac-fed6-b1151359d0a4
* Content: [Manage search verticals](https://docs.microsoft.com/en-us/MicrosoftSearch/manage-verticals)
* Content Source: [MicrosoftSearch/manage-verticals.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-verticals.md)
* Service: **mssearch**
* GitHub Login: @jypal6
* Microsoft Alias: **jypal**

**Comment by jypal6** [comment]
Thanks for the feedback. The article containing all government cloud support content will be updated to reflect this ask to maintain all content related to gov clouds in one place.
