### ISSUE TITLE
Meta tags not listing when configuring search connector with enterprise website data source

### ISSUE THREAD

**Issue by VikramAIS** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#275]
I have an enterprise website with OAuth enabled. While configuring the search connector meta tags are not listed on configuration settings page. If I disable the authentication then the meta tags list is shown as expected.  I am following the article https://docs.microsoft.com/en-us/microsoftsearch/enterprise-web-connector#step-3a-meta-tag-settings. 

Please help me with this.

**Comment by mecampos** [comment]
Hi @VikramAIS, please send an email to: MicrosoftGraphConnectorsFeedback@service.microsoft.com, with a link to this issue.
Include your tenant ID, and if possible, include screenshots of the results you are getting.
