### ISSUE TITLE
Enterprise Websites Connector for public facing websites

### ISSUE THREAD

**Issue by mfishman75** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#276]
I noticed that this article states that the Enterprise Websites Connector can be used for internal-facing websites. I have successfully used the connector with public facing sites. Is there a specific reason (acceptable use, licensing, etc.) that the article makes the specific distinction that the connector can only be used for internal-facing sites?

**Comment by mecampos** [comment]
Hello @mfishman75, thank you for bringing this up, I am going to confirm if this was updated or changed recently and will get back to you with answer.

**Comment by mecampos** [comment]
Hi @mfishman75, the Enterprise websites Microsoft Graph connector can be used for a public website. As a customer, you can set up and crawl public sites, and it will work as it did in your case; however, you will see a disclaimer message from Microsoft letting you know the terms of use of publicly available data in your Microsoft 365 tenant, indicating that it's use will be at your own risk. Please make sure you review the disclaimer for more details.
