### ISSUE TITLE
Outlook Search History Export is broken

### ISSUE THREAD

**Issue by bcihak** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#277]
[Enter feedback here]
When you navigate to https://myaccount.microsoft.com/settingsandprivacy/privacy and select "Privacy" then under Data Options "Microsoft Search History"...this feature is no longer working.  It does not export the OWA search history report like it use to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21c56af-67d4-48df-370a-545d9e92d0e7
* Version Independent ID: a83b1eb0-1361-066a-bbe4-3f7ef4a219e0
* Content: [Microsoft Search Overview](https://docs.microsoft.com/en-us/microsoftsearch/overview-microsoft-search)
* Content Source: [MicrosoftSearch/overview-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/overview-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by tklarsen** [comment]
We fixed the issue, and the download of search history is working again.

**Comment by tklarsen** [comment]
Closing the issue

**Comment by bcihak** [comment]
Thank you Tklarsen!  Confirming it's working again.

**Comment by bcihak** [comment]
Is there any chance on having the report capture the IP Address related to the search term?

**Comment by tklarsen** [comment]
Bcihak, capturing the IP address is not on our current plan.

**Comment by tklarsen** [comment]
Closing this one now.
