### ISSUE TITLE
Broken Link at the bottom of the Page

### ISSUE THREAD

**Issue by ssomu-ms** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#279]
Hi,
  The hyperlink for 'View search usage reports in modern sites' appears to have a .md at the end, generating a 404 response. The extension needs to be removed, to make the link as below:
https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports-modern-sites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37967c2e-89bc-9a30-062f-5ced811e9c46
* Version Independent ID: 0f4f3219-9b95-2dfb-8de3-9daaf8447766
* Content: [Search Usage Reports](https://docs.microsoft.com/en-us/microsoftsearch/usage-reports)
* Content Source: [MicrosoftSearch/usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/usage-reports.md)
* Service: **mssearch**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by jeffkizn** [comment]
@efrene please review.

**Comment by efrene** [comment]
This issue has been fixed. Thanks!
