### ISSUE TITLE
Location data labels include building number - How to make this work?

### ISSUE THREAD

**Issue by wese-de** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#280]
We have building plans that use numbers for individual workplaces that include the building number. For example we are in building 130 on the second floor in an open space setup. Our facility management has labeled each desk with an individual number, and that number is picked up by floor plan. The DWG label would look like this: 130219025 -> 130 = building, 2 = floor, 19 = openspace area, 025 = desk (The last two items could of course be combined to 'room' 19025).

The mapping seems to expect the DWG room label to NOT include the building code to do its magic. Is there any way to make this work without changing the room labels? So far my attempts have not succeeded.

Thank you, Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e310a1cf-f2d0-0613-51ae-2fb6646ac4e1
* Version Independent ID: fae06982-6bfa-2cc7-8507-18fa721f5972
* Content: [Manage floor plans](https://docs.microsoft.com/en-us/microsoftsearch/manage-floorplans?WT.mc_id=365AdminCSH_SupportCentral)
* Content Source: [MicrosoftSearch/manage-floorplans.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-floorplans.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by wese-de** [comment]
Oh, i am sorry for not specifying our AAD value. How clever of me.
A current real life example would be this string '130 2. OG 2190125'. It includes the building (130) and floor (2. OG = german for second floor) and the room (now: desk) which includes the floor number. Our DWG label would be called '130219025' making it unique in the plans of our facility management.
When following step 8 (location pattern) I put the floor as '2' and the room as '19025', but this didn't match anything on the final result screen. 
Since we are switching from room numbers to desk numbers, it would be possible to drop the '2. OG' in the office field as it is kind of redundant, but I still believe that the algorithm doesn't expect the building number as part of the room label. Is that correct?
Michael

**Comment by dawholl** [comment]
@wese-de Michael, as far as I'm aware, including the building code in the DWG labels shouldn't be an issue after specifying the location pattern. I'm going to start an email thread with the feature crew for floor plans to get clarification on this. I'll comment here as soon as I know more.

**Comment by dawholl** [comment]
@wese-de Michael, the floor plans feature crew is investigating this issue. I'll share more information as soon as I have it. Thank you for your patience.

**Comment by dawholl** [comment]
@wese-de Michael, a software engineer on the floor plans feature crew got back to me with this finding from his investigation:

> The admin was correct that the mapping does not expect the building code to be part of the DWG labels, which is the primary source of the issue.
>
> The best solution would unfortunately be to update the DWGs and remove the ‘130’ from all of the labels.
> 
> A workaround they could try is setting the floor to ‘130’ and the wing to ‘2’ while setting up the floor plan. I was able to get the mapping to work by doing that. However I cannot guarantee there won’t be some kind of unexpected side effect elsewhere by treating the building code as a floor and the floor as a wing.

I'm closing this issue with this comment. If you have other questions about floor plans, let me know.

-dawn
