### ISSUE TITLE
No Office Locations found in AAD

### ISSUE THREAD

**Issue by dopeyjone** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#281]
It's been around 4 days and it seems the building code isn't within AAD.
I have multiple users with office locations G/1001.. G/1009. These locations are showing up in their user profile if I search within Bing but the building code is not being recognized when adding the floorplan.
Users are also not being automatically mapped even though it recognizes all the text labels within the dwg file

It's been 4 days since I've edited my users.
Am I doing misunderstanding something or am I doing something wrong here?

**Comment by dawholl** [comment]
@dopeyjone, a couple of questions:
1. Do you have a location answer for your building G?
2. When you upload the DWG file are you prompted for a building code? If so, what error are you getting after you enter the building code?

**Comment by dawholl** [comment]
@dopeyjone, since there's been no reply I'm closing this issue with this comment.
