### ISSUE TITLE
Current import functionality does not match description

### ISSUE THREAD

**Issue by ekdegerman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#29]
The bullet point below from the important points section under "Bulk add or edit bookmarks" does not seem to be correct. When I try it in my tenant, bookmarks that match existing titles and/or URLs are listed as errors that prevent import.
"If there is an existing bookmark with the same title or URL, the bookmark will be updated with information in the import file."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86601b66-7664-6062-d56b-70e53dfbdc36
* Version Independent ID: 4b17efd0-658b-9a68-04d3-ea1aaa0a619c
* Content: [Manage bookmarks](https://docs.microsoft.com/en-us/microsoftsearch/manage-bookmarks#feedback)
* Content Source: [MicrosoftSearch/manage-bookmarks.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-bookmarks.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by adefowler** [comment]
Thanks! @ekdegerman - We'll get this updated! I'll let you know when it's done (probably November 4th).

**Comment by jeffkizn** [comment]
Thanks for the feedback @ekdegerman. We have updated the content on the page to better reflect the import behavior and how to prevent errors and duplication.
