### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#3]
I am not seeing the ability to show Business results or Conversation results in my tenant. How do I activate that functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc7364e-7355-3a20-fee1-14a9ff3f25d0
* Version Independent ID: 9396844d-301a-f38c-c147-16332b5b80b1
* Content: [Content settings](https://docs.microsoft.com/en-us/microsoftsearch/content-settings)
* Content Source: [MicrosoftSearch/content-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/content-settings.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by WendyStidmon** [comment]
![image](https://user-images.githubusercontent.com/51454343/59049432-cbcaed80-883c-11e9-8108-59348c19fc57.png)
