### ISSUE TITLE
Lack of clarity on how an ACL would be specified

### ISSUE THREAD

**Issue by mikewalker74** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#30]
The documentation doesn't describe how ACL's would need to be presented as SQL Server Databases dont generically have ACL's at row level without being on a later version. Would be good to have reference documentation to explain how the connector needs to map ACL's? Is an ACL the Azure AD ID is there multiple ways to present this. What about azure groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Microsoft SQL connector for Microsoft Search](https://docs.microsoft.com/en-us/MicrosoftSearch/mssql-connector#feedback)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray
* Microsoft Alias: **v-pamcn**

**Comment by monaray97** [comment]
Hi @mikewalker74 thank you for reaching out about this confusion. We are in the process of updating this article to reflect the answers to your questions. I will let you know once it has been updated. Please let me know if you have any other questions! :)

**Comment by monaray97** [comment]
Hi @mikewalker74, the docs have been updated. Please see https://docs.microsoft.com/en-us/MicrosoftSearch/mssql-connector for the latest updates. Thanks!
