### ISSUE TITLE
Very Minor Typo

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#35]
The link to the article "See Install and on-premises gateway to learn more." Should be "See Install **an** on-premises **data** gateway to learn more."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Microsoft SQL connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector?source=docs#feedback)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @monaray
* Microsoft Alias: **mounika.narayanan**

**Comment by adefowler** [comment]
Thanks, @MatthewMcD 

I fixed it and am pushing the change to live now. Wait about 30-ish minutes to see the changes.
