### ISSUE TITLE
File Share Connector

### ISSUE THREAD

**Issue by WorTony** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#36]
Does Microsoft Search and the Files Connector suppler CIFS file shares?

**Comment by monaray97** [comment]
Hi @WorTony, thank you for your question. CISF file shares is an enhanced version of SMB. As of today, we support only SMB. So if you were to use our connector for CISF, some of the functionalities might not work as they should; and we are not sure which will work and which won't. Let us know if you have any other questions!
