### ISSUE TITLE
Not available in the UK

### ISSUE THREAD

**Issue by MartinEngGit** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#39]
Microsoft support have informed me that this preview is not currently available in the UK. Perhaps this page can be updated to show where it is available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd23754-25c0-73b1-2201-2482f98e6a4b
* Version Independent ID: d9e5fe5f-2a91-b3b9-769f-8e9952fcdb1e
* Content: [Connectors preview](https://docs.microsoft.com/en-us/MicrosoftSearch/connectors-preview#feedback)
* Content Source: [MicrosoftSearch/connectors-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/connectors-preview.md)
* Service: **mssearch**
* GitHub Login: @monaray
* Microsoft Alias: **mounika.narayanan**

**Comment by monaray97** [comment]
Under the preview limitations section, I have updated that information. Thank you for pointing this out!

**Comment by monaray97** [comment]
The update to the public documentation

**Comment by monaray97** [comment]
Hi @MartinEngGit, I have an update from our team. We are now working to open up connectors to regions that are currently blocked, such as the UK and France. Our team will notify you and others once it is available. Thank you for your patience!

**Comment by expiscornovus** [comment]
Hi @monaray97, just to clarify. Do you mean open up connectors in the UK and France for the preview program?

**Comment by monaray97** [comment]
Hi @expiscornovus, the connectors preview program is now open to tenants registered in the UK and France.
