### ISSUE TITLE
Missing Building Codes in Microsoft Search

### ISSUE THREAD

**Issue by skasab** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#40]
We're attempting to upload office floorplans into Microsoft Search in Bing, but we are hitting a snafu in the building code selection.

Despite the fact that the chosen employees have an Office field such as DC/001 in Azure AD, the wizard still indicates that the building code is incorrect. The office field we're using is in line with the Microsoft Docs example, such as B1/1001, so it's not a formatting error.

Our location data is proper, yet we still cannot proceed past this step despite having a proper building code. Image attached. Any and all ideas would be appreciated. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/36207625/72292711-f0cbde00-361f-11ea-993f-2f8017a0eee0.png)

**Comment by rasrivas-ms** [comment]
I had a few queries about this:
Did you update the office location recently i.e. 2-3 days before uploading floor plans?
If the answer to (1) is yes, then can you try the upload again and check whether it works now?
Rahul Srivastava
Microsoft

**Comment by rasrivas-ms** [comment]
Hi,

Did the issue you reported get resolved or did you get a chance to contact support?

Thanks,
Rahul
