### ISSUE TITLE
needs sample DWG files

### ISSUE THREAD

**Issue by willgart** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#42]
a sample DWG file will be really helpfull to start creating our plans.
and a process to use Visio and convert to DWG will be great too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e310a1cf-f2d0-0613-51ae-2fb6646ac4e1
* Version Independent ID: fae06982-6bfa-2cc7-8507-18fa721f5972
* Content: [Best practices for Microsoft Search floor plans](https://docs.microsoft.com/en-us/microsoftsearch/floorplans-bestpractices#feedback)
* Content Source: [MicrosoftSearch/floorplans-bestpractices.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/floorplans-bestpractices.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by TonythaMsft** [comment]
Thanks for the feedback. Floor plans are associated with buildings in your enterprise and with office locations specified in your employee AAD profiles.

Could you explain how floor plans are created in your organization and how you think a sample DWG file can help? What are you looking for in the sample DWG file? are you trying to test this on a test tenant?

This will help us understand your feedback better and address to it.

**Comment by TonythaMsft** [comment]
Thank you for the feedback. These are valuable inputs and we are looking into this.
