### ISSUE TITLE
Open Seating

### ISSUE THREAD

**Issue by Heidi-Connor** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#43]
In our office, we have several areas with open seating, which results in multiple employees having the same location in Azure, for example, L1-OPEN. Will this cause problems mapping locations? I'm able to import my file, and it claims it has a people count of 30, but it does not work.  "In the floor plan, the office locations must be unique and cannot repeat. For example, if two people share office 2/1173, 2/1173 can only have one unique instance in your floor plans, but the user accounts in Azure AD will both have the same office location."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0c9359-bfda-34f9-4cd5-4522751cc986
* Version Independent ID: 1a13448f-3931-c2e8-362f-26fc6d13d594
* Content: [Manage floor plans](https://docs.microsoft.com/en-us/microsoftsearch/manage-floorplans#feedback)
* Content Source: [MicrosoftSearch/manage-floorplans.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-floorplans.md)
* Service: **mssearch**
* GitHub Login: @rasrivas
* Microsoft Alias: **rasrivas**

**Comment by TonythaMsft** [comment]
Hi, 
Could you please clarify what you mean by "it does not work"? The implementation expects that you have a label L1-OPEN in your DWG file and your employees have this in their AAD profile as well.

Also, what does L1 in the floorplan refer to?

**Comment by Heidi-Connor** [comment]
Hi Tony, Sorry I was vague. The import didn't produce an error, but when I use Bing to search for the user, the user profile card shows their location, but it is not an active link, and there is no Office tab on the card. I have been able to successfully import buildings for another location, but not this one.

The user I'm looking at does have an assigned seat, L1-122.H. L1 is the floor, 122.H is the office. In regards to the L1-OPEN label, there are a bunch of users who do not have assigned seating. They all have the same L1-OPEN label. I don't expect those to show up in results, as it would not be useful, but I am concerned that they might be causing an import issue?

When I import, it says it found 30 users, but none of their user cards appear with the Office tab in Bing search results. I checked again this morning (over 96 hours since being added).

**Comment by rasrivas-ms** [comment]
Hi,

Can you submit a feedback through the 'Give Feedback' link at the bottom-right of the admin portal? We can then help troubleshoot the issue.

Thanks,
Rahul

**Comment by rasrivas-ms** [comment]
Hi Heidi,

Gentle ping. Did you get a chance to submit the feedback?

Thanks,
Rahul

**Comment by Heidi-Connor** [comment]
Hi Ruhal!

Yes, I did it the same day you posted the suggestion. I currently have an open ticket with support on the issue.

Thanks for your assistance, much appreciated.
Heidi

**Comment by Heidi-Connor** [comment]
The issue turned out not to be related to the open seating. Microsoft was able to fix something on the back end that un-stuck the import and got things working. All is now good and my imports now show the correct number of seats and work grand.

**Comment by rasrivas-ms** [comment]
Great. Should we consider this issue resolved?
