### ISSUE TITLE
Verticals option missing 

### ISSUE THREAD

**Issue by imran-siddique** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#45]
Hi,
When I go to my Admin Center (https://admin.microsoft.com/AdminPortal/Home#/MicrosoftSearch), I don't see the Verticals tab anywhere. 

I am referring this - 

"In the Microsoft 365 admin center, go to Settings &gt; Microsoft Search &gt; Verticals."

Thanks
Imran 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-us/MicrosoftSearch/customize-search-page#feedback)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by jeffkizn** [comment]
At this time, Verticals is only available to customers that have been onboarded to the preview of Graph Connectors. If your tenant has been onboarded to the Connectors preview and you are not seeing the Verticals tab, please contact support for the Connectors preview.

https://docs.microsoft.com/en-us/MicrosoftSearch/customize-search-page
DISCLAIMER: Verticals and result types are currently in preview as a part of the Microsoft Graph connectors preview. You can't create a vertical for content residing in SharePoint or from content indexed by the file share connector. To find out more about the preview, see Connectors Preview. To participate in the preview, you must first submit the Microsoft Graph Connectors Preview Signup form.
