### ISSUE TITLE
Expand scope of Top Search and Impressions data

### ISSUE THREAD

**Issue by Heidi-Connor** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#47]
Only a small subset of our users search via Bing Search, so these stats, though lovely, are not reflective of our actual user base. I'd like to suggest that they be expanded to include all Org level searches, regardless of where the search originates. That would make the dashboard much more valuable.

**Comment by jeffkizn** [comment]
Thank you for your comment. We are, indeed, working on expanding the scope of search usage analytics. We discussed the situation, plans, and timelines recently at Ignite. You can watch that session at https://myignite.techcommunity.microsoft.com/sessions/81164.

**Comment by RobOK2050** [comment]
Is there any update on when this feature is coming. Right now our Insights are blank 100% of the time as no one uses Bing in our organization.
