### ISSUE TITLE
Log on Microsoft Search Link is incorrect

### ISSUE THREAD

**Issue by v-alhuil** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#48]
[When you first go to Microsoft Search in the Microsoft 365 **admin center**, you enter on the Insights dashboard.]
It cannot be accessed via the link above, it should be visited via: https://www.bingforbusiness.com/admin/

Click the Service & Add-ins - Microsoft Search will not direct users to the good place. 

Please advise the link. 

Thank you,

Alison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37967c2e-89bc-9a30-062f-5ced811e9c46
* Version Independent ID: 0f4f3219-9b95-2dfb-8de3-9daaf8447766
* Content: [Microsoft Search Insights dashboard reports](https://docs.microsoft.com/en-us/microsoftsearch/get-insights)
* Content Source: [MicrosoftSearch/get-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-insights.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by jeffkizn** [comment]
Hello Alison,

The link you have provided to the bingforbusiness/admin site is no longer correct. If you visit that site, it will redirect you back to the Microsoft 365 Admin center which is the appropriate location for all Microsoft Search administration. The documentation appears to be correct in providing https://admin.microsoft.com as the link. Can you explain more about the problem you are facing?

**Comment by v-alhuil** [comment]
@jeffkizn Hi Jeff,

Thank you for your reply. 

We had a cx 2 days ago stating Bookmarks in Microsoft Search not function correctly. 
And then I realized I did not have Microsoft Search under my Preview AC - Settings. I tried to see the deployment in Preview, but it did not return a result; then I went back to Old AC to check the Add-in Deployment to confirm it was enabled, then I switched back to Preview AC, still no luck.
Then I pasted that bingforbusiness/admin site in a new tab under FireFox with my AC opened, it did redirect me to sign in with credentials again - then it gave me the Microsoft Search. Today I can see it under my Preview AC - Settings. 
Maybe it is just happening on my lab account that is never manually touching that feature under AC. Also, I think we should direct the user to their Preview AC **- Settings**, along with the link.

Thank you,
Alison

**Comment by jeffkizn** [comment]
Alison,
As you noted, Microsoft Search is only available when you have Microsoft Admin center set to the new experience, and this requirement is mentioned in our docs. It's not clear to me why you had to toggle that setting a couple of times in order to see it, but it sounds like an anomaly. We'll keep an eye out for other reports of this behavior.

Thanks very much,
-jeff
