### ISSUE TITLE
Internationalization on searched terms

### ISSUE THREAD

**Issue by klaaslauwers** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#5]
Does internationalization work on search terms? By which I mean: if you search for “car” in English, will it automatically search for “auto” in Dutch/German as well? Same question for other language processing steps such as stemming, strange character trimming. 
Thanks in advance! 
Kr
Klaas

**Comment by WendyStidmon** [comment]
![image](https://user-images.githubusercontent.com/51454343/59049432-cbcaed80-883c-11e9-8108-59348c19fc57.png)

**Comment by klaaslauwers** [comment]
Thanks for the reply @WendyStidmon 

I've asked my question in the support forum. I will close this one and follow up over there.
