### ISSUE TITLE
Bookmarks sharing the same keyword: Only 1 result is displayed

### ISSUE THREAD

**Issue by Anonimiss** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#51]
The documentation states:
"A bookmark can have several keywords and several bookmarks can share the same keyword, but reserved keyword can't be shared. ".

This needs to be clarified. I have several bookmarks sharing the same keyword, but search will only display one.  Is that working as intended? If so, how does search decide which bookmark to display based on the same keyword?  

If you are specifying bookmarks can share keywords, then my expectation is that all bookmarks with the shared keyword would display when the user searches that keyword.

**Comment by tanaybaldua** [comment]
Hi Anonimiss
Firstly apologies for reverting with a delay on this issue as I was facing access problems to Github.
 Please find my responses to your queries.

"A bookmark can have several keywords and several bookmarks can share the same keyword, but reserved keyword can't be shared. ". : **_You are correct, reserved keyword has to be unique._**

I have several bookmarks sharing the same keyword, but search will only display one. Is that working as intended? : **_I would like to know what is the canvas you are seeing this experience. As per my understanding, on Bing/Sharepoint/Office - you can see multiple bookmarks in Answer.One of them will be the main one and others will appear in related bookmarks section. Refer image below._**
![image](https://user-images.githubusercontent.com/61873462/76085073-4fd22180-5fd7-11ea-8d04-2fd7f18d317e.png)

If so, how does search decide which bookmark to display based on the same keyword? : **_This is based on multiple ranking logic we have defined at our end. In case you want a particular Bookmark to be given high importance over others, put the common keyword as "Reserved keyword" for it_**

Let me know if any other issues.

Regards
Tanay

**Comment by Anonimiss** [comment]
Thank you, tanaybaldua.  Your response helps me understand the expected behavior of bookmarks.  

In the past, I utilized Query Rules to surface important content in SharePoint's search results.  Similar to bookmarks, I could have several query rules with the same phrase, but the results appeared differently:
![76085073-4fd22180-5fd7-11ea-8d04-2fd7f18d317e](https://user-images.githubusercontent.com/11741679/76459646-2ed84a80-63a2-11ea-97b2-fd2f02767321.png)

Your explanation helps me understand clearly how multiple results appear.  While I think the other items sharing the keyword somewhat get lost, it at least now makes sense how it is working behind the scenes. 

Thanks again.
