### ISSUE TITLE
The 'manage locations' page has 'important points' related to bookmarks

### ISSUE THREAD

**Issue by rasrivas-ms** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#52]
Here are some important points regarding the template file:

Never edit data in these fields: Id, Last Modified, and Last Modified By
If you include the Id of an existing bookmark, it will be replaced with the information in the import file.
If there is an existing bookmark with the same title or URL, the bookmark will be updated with information in the import file.
Not all fields in the template file are required and required fields vary depending on the bookmark state.
Based on the State field, bookmarks will be saved as draft, suggested, scheduled, or they will be published automatically.
For partners who manage multiple organizations, you can export your bookmarks from one org and import them into another. But you must remove the data in the Id column before you import.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79763408-6d1b-3ae3-39cb-064cbb329109
* Version Independent ID: ac060ac0-2938-ed28-0b65-a7b04802d575
* Content: [Manage locations](https://docs.microsoft.com/en-us/microsoftsearch/manage-locations?source=docs#feedback)
* Content Source: [MicrosoftSearch/manage-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-locations.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by jeffkizn** [comment]
Thanks for reporting this; we will get the docs updated.

**Comment by jeffkizn** [comment]
The doc have been updated.
