### ISSUE TITLE
Microsoft Search beta is limited to a small set of pilot users at this time

### ISSUE THREAD

**Issue by filipvancanneyt** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#53]
our users still receive this notification when login in with their work account on bing.com
is Microsoft Search already Generally available ?
is ther eany way to force this on our subscription ?

Filip

**Comment by jeffkizn** [comment]
@filipvancanneyt - Thanks for reporting this ;can you please paste in a picture of the notification?

**Comment by filipvancanneyt** [comment]
Hi, please find below a screenshot

![image](https://user-images.githubusercontent.com/61456397/75326467-f7827d80-587a-11ea-9c26-026549364481.png)

**Comment by mohitkhatri88** [comment]
@filipvancanneyt , Could you help us get some details about your tenant? If you can email msbDSAT@microsoft.com and start a thread, we can help you out with fixing the issue.

Thanks,
Microsoft Search

**Comment by jeffkizn** [comment]
@filipvancanneyt - Thanks for the picture. We believe we understand the issue and are working to resolve it. We'd like to confirm some details from your tenant so that we can validate the fix. Can you logon to the Microsoft Search admin center and use the feedback widget on the page to report this. That will allow us to get your tenantID and confirm the issue.

**Comment by filipvancanneyt** [comment]
@Jeffkizn , @mohitkhatri88 , I have provided the feedback and mailed tenant info to msbDSAT, this mail returned as I'm not allowed to send to it.
please let me know if you need additional info.

**Comment by filipvancanneyt** [comment]
Hi,

I’m not allowed to send to msbDSAT, please provide another mail address ?

Kind regards
Filip

**Comment by jeffkizn** [comment]
@filipvancanneyt 
Filip - Thanks for your patience here. We have everything we need from your feedback submission and do not need you to send a separate email. Standby while we complete the investigation. We'll come back and confirm resolution with you, presently.

-jeff

**Comment by mohitkhatri88** [comment]
Hi Filip, 

We have a fix in place. User's in your company should now be able to login to bing using their work account without problem. Do let us know in case of any issues.

Mohit

**Comment by filipvancanneyt** [comment]
Hi, several users tested this, and it seems ok.
any info about the fix, was it somethinh we could adapt ?
thx for the support

**Comment by jeffkizn** [comment]
There was a flag on your tenant that should have cleared but somehow persisted when we moved from preview into general availability. We cleared that flag on the backend and scanned for any other customer that may have been in a similar state. This is not something you could have changed on your own.
