### ISSUE TITLE
Microsoft Graph connectors and Microsoft Search API — Preview Access?

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#54]
I'm trying to prototype a solution for a client and am looking to gain access to the connectors preview program and to test the new search APIs for externalItems. I've completed the sign-up form located at the following URL but have not yet heard back.

https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta

Any guidance would be much appreciated on this process!

**Comment by monaray97** [comment]
Hi @patrickabel your tenant has been submitted for enablement. Our team will send out an email once the changes have been confirmed. Thanks for your patience!

**Comment by patrickabel** [comment]
thank you!

**Comment by Robyskariah** [comment]
Any idea on how I can enable in my dev tenant as well? I have the same issue on ServiceNow connector for Microsoft Search. I have submitted a Preview sign up program as well. Never heard back on this. Would like to try this in a dev tenant before we sign up in our org prod tenant.

**Comment by monaray97** [comment]
Hi @Robyskariah we are currently in the process of rolling out Connectors to all of Targeted Release Ring (ETA mid-June). Because of this, we have halted manual enablement of Connectors on individual tenants.
