### ISSUE TITLE
Delay before results appear?

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#55]
Is there a delay between when the floor plans are uploaded and matched to AAD data and when those results appear in a Bing search?

I've uploaded floor plans and the wizard said staff mappings were matched and complete. I reviewed the details and observed correct matches between the plans and the location data. When I search in Bing, the map option doesn't appear with the person's record. Our office numbers on the maps are in the format &lt;floor&gt;-&lt;office number&gt; i.e. 01-23, because we don't have multiple buildings, my understanding is this should work and we don't need a building designation (in fact the wizard skips this step).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0c9359-bfda-34f9-4cd5-4522751cc986
* Version Independent ID: 1a13448f-3931-c2e8-362f-26fc6d13d594
* Content: [Manage floor plans](https://docs.microsoft.com/en-us/microsoftsearch/manage-floorplans#feedback)
* Content Source: [MicrosoftSearch/manage-floorplans.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-floorplans.md)
* Service: **mssearch**
* GitHub Login: @rasrivas
* Microsoft Alias: **rasrivas**

**Comment by rasrivas-ms** [comment]
Hi,

It takes about 24-48 for floor plans to be published.

Thanks,
Rahul

**Comment by rasrivas-ms** [comment]
@cchambers-cap Are you seeing the floor plans now?

**Comment by cchambers-cap** [comment]
Yes, thanks!
