### ISSUE TITLE
missing 'Floor plans' option

### ISSUE THREAD

**Issue by MarekKrzyszton** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#57]
Hello,
I can't find the 'Floor plans' option in the Settings -> Microsoft Search 
Am I missing something in configuration? I'm global admin...

![image](https://user-images.githubusercontent.com/50481193/76940822-3b592780-68fb-11ea-8291-a71662b6aa1f.png)

Regards,
Marek

**Comment by jeffkizn** [comment]
Floor plans is in the process of completing rollout to all customers; it is not available to everyone yet. The rollout will complete presently and you should see it at that time.
