### ISSUE TITLE
License requirements

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#59]
Can you please provide details about licensing of Microsoft Search?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af30bbd-1bc5-5026-87d9-8aa40de2489e
* Version Independent ID: ffb6b68d-57ff-270e-1b63-d7175a5b61d3
* Content: [FAQs](https://docs.microsoft.com/en-us/microsoftsearch/faqs)
* Content Source: [MicrosoftSearch/faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/faqs.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
Microsoft Search is part of Office 365. There are no specific licensing requirements on top of Office 365 SKUs.

**Comment by Larryngolog** [comment]
There is definitelly need for E3/E5 to use connectors. Do you need office 365 suite (Business/F/E/A) or can you use Microsoft Search with SPO plan 1 standalone?

**Comment by jeffkizn** [comment]
There are features where specific license requirements may be needed, like Connectors. These cases are called out in the specific documentation section for those features. SPO plan 1 does allow for the use of Microsoft Search.

**Comment by Larryngolog** [comment]
Thanks @jeffkizn. Do you think it would make sense to add my question and your answers to this FAQ?

**Comment by jeffkizn** [comment]
As a general rule, we try to stay away from that when there isn't anything specific about the feature and is just part of Office 365 SKUs. But it's something we'll look at with the appropriate teams and determine if it makes sense. Thanks for your comments; I appreciate it.
