### ISSUE TITLE
Search results display on office.com

### ISSUE THREAD

**Issue by klaaslauwers** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#6]
When will it be possible (and is it going to?) to have the search results on office.com displaying and/or behaving like the bing search results? Will it be possible also to launch this from windows 10 or even from within SharePoint directly?

**Comment by tklarsen** [comment]
The answer to some of your questions is yes, learn about Microsoft Search in SharePoint, Bing, office.com and more in https://docs.microsoft.com/en-us/MicrosoftSearch/overview-microsoft-search

**Comment by klaaslauwers** [comment]
Hi @tklarsen,

Thanks for the reply. This doesn't answer my question though :-). I went through the entire documentation available and didn't find anything that could help me answer my question. 

Any other pointers / insights? 

Thanks in advance!

**Comment by tklarsen** [comment]
Hi @klaaslauwers,
Sorry, then I didn't understand your questions right :-( For the first question, did you mean whether search results on office.com will be look the same as the work results in Bing?
