### ISSUE TITLE
Licensing requirements for SharePoint - Online and On-prem

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#60]
What license is required to perform searches in SharePoint Online?
What licesne is requried to perform searches in SharePoint On-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f13f-b678-3cb0-58e3-4e798201aa7a
* Version Independent ID: fe5470d4-8703-2ce3-7cf6-b53416f13199
* Content: [Get started with Microsoft Search in SharePoint Online](https://docs.microsoft.com/en-us/microsoftsearch/get-started-search-in-sharepoint-online)
* Content Source: [MicrosoftSearch/get-started-search-in-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-started-search-in-sharepoint-online.md)
* Service: **mssearch**
* GitHub Login: @tlarsen
* Microsoft Alias: **tlarsen**

**Comment by jeffkizn** [comment]
Microsoft Search is included in SharePoint Online licenses. If you connect to your on-premises infrastructure via SharePoint hybrid, you on-prem data will also be returned in Microsoft Search

**Comment by Larryngolog** [comment]
Thank you!
