### ISSUE TITLE
guidance re 365 search

### ISSUE THREAD

**Issue by choccieman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#61]
As insights currently say data is limited to Bing results, can a timeframe be added for when the data will include 365 search queries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37967c2e-89bc-9a30-062f-5ced811e9c46
* Version Independent ID: 0f4f3219-9b95-2dfb-8de3-9daaf8447766
* Content: [Microsoft Search Insights dashboard reports](https://docs.microsoft.com/en-us/microsoftsearch/get-insights#feedback)
* Content Source: [MicrosoftSearch/get-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/get-insights.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by jeffkizn** [comment]
Target dates are this summer.
