### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#62]
"as well as the internet in the user’s organization."
I wonder if it refers to the intranet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df67176-e302-f972-dbf7-d7e0747e5bd2
* Version Independent ID: e213129d-0fb1-31ee-a654-091d032c2746
* Content: [Set up Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search)
* Content Source: [MicrosoftSearch/setup-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/setup-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by jeffkizn** [comment]
Internet is intended here as Microsoft Search in Bing allows for internet search in combination with intranet, but I do see how the rest of the sentence makes this confusing. We will make that clearer.
