### ISSUE TITLE
Acronyms entered into Search Admin don't show up in Sharepoint

### ISSUE THREAD

**Issue by RobOK2050** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#64]
Acronyms defined in Search Admin only show up in Bing search. None of our users use Bing Search.

At the very very bottom of this page:
https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms

It says only Bing, even though throughout that whole page it says Bing, Office 365, and Sharepoint Online. 

When is the this search feature going go work in Sharepoint Online?

**Comment by anrasto** [comment]
HI @RobOK2050 ,

Acronyms feature is currently only available in Bing.com. We are working hard on getting it to Sharepoint Online and Office.com.

Apologies for the confusion caused by the doc and thanks for bringing it to our notice. We will update the doc accordingly

**Comment by RobOK2050** [comment]
Ankit, 
Thanks for the response, it is much appreciated. Is there any timeline? We are rolling out a new portal and wanted to include that feature in our training. Can you specify a Quarter when that might show up?

**Comment by anrasto** [comment]
Hi Rob,

We are working hard on getting Acronyms to SharePoint online and Office.com. Right now we are not able to provide an exact view into the timelines but we expect this to land sometime in Q4, CY 2020.
