### ISSUE TITLE
Issue with Search Connectors

### ISSUE THREAD

**Issue by andrei-zmf** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#65]
Hello dear Microsoft, 

We have configured a new Microsoft Search connector and loaded some data. However, we are not able to see the results in the search center and receive the following error:
"Something went wrong"
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/47849505/83800016-660f7c80-a6af-11ea-9e85-da3545968fdf.png)

As per this troubleshooting guide this error should be caused by missing vertical or result type and that they are configured for the same connection. We checked and everything is configured correctly on our side, please check screens. We noticed there is an error when we try to access details for Result Type.

![Capture Connection info](https://user-images.githubusercontent.com/47849505/83800792-b935ff00-a6b0-11ea-8ad6-2ca22ce05264.PNG)
![Capture Result Source Error](https://user-images.githubusercontent.com/47849505/83800797-b9ce9580-a6b0-11ea-83b0-05107315b48f.PNG)
![Capture Result Source](https://user-images.githubusercontent.com/47849505/83800799-b9ce9580-a6b0-11ea-9185-7d7a56d8e768.PNG)
![Capture Search Vertical](https://user-images.githubusercontent.com/47849505/83800800-ba672c00-a6b0-11ea-8aa8-942733ffa520.PNG)

Another issue is that the Edit button from the connection details modal is not functional.

Our tenant address is: be4youtest.sharepoint.com
Pleas let me know if you need more details on this matter.

Thank you,
Andrei Zamfirescu.

**Comment by monaray97** [comment]
Hi @andrei-zmf, thanks for reaching out. I have opened a bug to investigate the "Something went wrong" issue you are facing. Could you please provide more information around the Edit button from the connection details modal not being functional? Is the button not taking you to the connection flow? Any additional information regarding this issue would be greatly appreciated.

**Comment by andrei-zmf** [comment]
Hi @monaray97 , thanks for the reply. Details button does nothing on clicking. We can also schedule a call if you want and i can show you the behavior. 

Thank you,
Andrei.

**Comment by monaray97** [comment]
Hi @andrei-zmf, thanks for clarifying the issue. I'd love to hop on a call to discuss further. Please reach out to MicrosoftGraphConnectorsFeedback@service.microsoft.com and we can follow up.

**Comment by marcofong** [comment]
Hi Microsoft,

I´ve been struggling for while with the process of creating a new custom Azure DevOps Connector to my Microsoft Search section but I receive a 400 error when I click on Login (step 2, when M365 start authenticating through DevOps), and everything seems to be fine. I´ve already registered the app on my DevOps instance and authorized it as well. Could you please address me to the get right way on this issue.     

 On the other hand, do you know if Microsoft has in its roadmap any connector to those virtual library platforms like Cornerstone?

Many thanks!

**Comment by monaray97** [comment]
Hi @marcofong, sorry you are having trouble with creating your custom ADO connector. Please reach out to MicrosoftGraphConnectorsFeedback@service.microsoft.com and our team would be happy to help.
