### ISSUE TITLE
No "Microsoft Search" section on SharePoint "View all settings" page

### ISSUE THREAD

**Issue by pleomorph** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#66]
I'm attempting to create a Search Vertical at a SharePoint _site_ level using the instructions below. However, I'm unable to complete Step 3.  There is no "Microsoft Search" section, nor is there a "Configure Microsoft Search for this site collection" link on the "View all site settings" page.
I am on a brand-new Dev tenant with the "Targeted Release" option enabled.  I can create Search Verticals at the _organization_ level, just not at the _site_ level.  Please advise.

Create a vertical at the site level

1. On the SharePoint site where you want the vertical, go to Settings.

2. Select Site information and then View all site settings.

**3. Look for the Microsoft Search section, and then select Configure Microsoft Search for this site collection.**

4. In the navigation pane, go to Custom experience, and then select the Verticals tab.

5. To add a vertical, select Add. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-us/MicrosoftSearch/customize-search-page)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @jypal
* Microsoft Alias: **jypal6**

**Comment by jeffkizn** [comment]
Thanks for trying out these features. The rollout for this in SPO site administration for Targeted Release track is expected to complete by June 10. Please check over the next few days for the inclusion of your tenant.

**Comment by jeffkizn** [comment]
This is fully rolled out to Targeted Release. If you are having trouble with it, I suggest opening a support case so that we can look at tenant specific information with you.
