### ISSUE TITLE
Are Search Connectors no longer in private preview?

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#67]
Is the disclaimer saying we need to sign up for private preview still valid? 

I have a targeted tenant and I can perfectly follow the docs and work with custom connectors as per documentation. 

Are we now in public preview? Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 479e5aa9-8bb8-69d5-b66c-fa37fc54dbed
* Version Independent ID: 7975a13e-cc2a-06c3-0212-0c085d5428ca
* Content: [Connectors Overview](https://docs.microsoft.com/en-us/MicrosoftSearch/connectors-overview)
* Content Source: [MicrosoftSearch/connectors-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/connectors-overview.md)
* Service: **mssearch**
* GitHub Login: @monaray
* Microsoft Alias: **mounika.narayanan**

**Comment by jeffkizn** [comment]
Connectors are still in preview, but are now available to all customers in the Targeted Release track.

**Comment by sebastianzolg** [comment]
@jeffkizn Thanks, but will you update the docs to reflect this by removing the disclaimer message right at the top? Otherwise, people will try to sign up for the preview, which is not needed anymore.

**Comment by jeffkizn** [comment]
The change to the disclaimer has already been made. If you are not seeing it, please clear your browser cache.

![image](https://user-images.githubusercontent.com/47789222/84157396-8c227d00-aa1f-11ea-8aa4-3850d0df37c6.png)

**Comment by sebastianzolg** [comment]
Brilliant @jeffkizn ! Thanks
