### ISSUE TITLE
Acronyms search without question

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#70]
Hi, currently Microsoft Search trigger Acronyms search only with questions.

Like "What is MSFT"? Return for example "MSFT if Microsoft Corporation". Will be also fine improvement, if allowed be searched also as exact data match. So searching only for "MSFT" will also return such result.

I see that we need for example mimic the same behave with Q&A and keywords with longer explanations to achieve same.

**Comment by RakeshMSFT** [comment]
Hi @Kazzan,

Thanks for sharing this valuable feedback with us. We understand that typing just the acronym without any patterns is easier for our users to query. This feature is currently in our backlog and our team is going to plan for this soon.
