### ISSUE TITLE
ServiceNow Connector issue - malformed 

### ISSUE THREAD

**Issue by drsoltis** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#71]
We have been trying to set up this connector from Azure to Service Now and while working with Service Now support teams it seems the Connector isn't sending the request correctly. In short, we target our instance of ServiceNow with oauth_token.do in the Connector URL. The request doesn't seem to be coming across correctly and we are being redirected to the front end SSO.  Could anyone help? They are saying request must be grant type password, client id, client secret, username, password

**Comment by monaray97** [comment]
Hi @drsoltis, sorry you are having trouble. If you could send an email to MicrosoftGraphConnectorsFeedback@service.microsoft.com, our team will be able to assist.
