### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by erichenson** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#72]
The correct path to Acronyms is Settings>Microsoft Search>Answers, not Settings>Microsoft Search>Acronyms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd51764-80a7-b404-50bd-b492b193dab2
* Version Independent ID: 62a6858b-81a3-bafa-4bcc-3bb2a951c654
* Content: [Manage Acronym answers in Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms)
* Content Source: [MicrosoftSearch/manage-acronyms.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-acronyms.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by jeffkizn** [comment]
We are in the process of rolling out a new look to the UI which your are seeing. It is not yet available to all customers, world wide. We are timing the update to the documentation to coincide with the completion of the rollout as it will include deep links to specific sections that will only work on the new UI and did not want any customer to have broken links in the doc. 

In the meantime, I hope you found the new UI discoverable so the discrepancy in documentation didn't matter and that you like the new look.

**Comment by jeffkizn** [comment]
We have completed the rollout of the new UI and updated the documentation to reflect it.
