### ISSUE TITLE
 Edge Legacy instead of edge

### ISSUE THREAD

**Issue by contactbrenton** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#73]
To download Edge extensions, go to Microsoft Store.

This is Edge Legacy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185973f2-cf73-9007-9eab-7e337705ed6e
* Version Independent ID: 49456178-689f-2e12-b0f3-57b294a4e82d
* Content: [Manage Q&As](https://docs.microsoft.com/en-us/microsoftsearch/manage-qas)
* Content Source: [MicrosoftSearch/manage-qas.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-qas.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by dawholl** [comment]
@contactbrenton, update to clarify Edge legacy and chromium for extensions/web stores is now live, https://docs.microsoft.com/en-us/microsoftsearch/manage-qas. Thanks for the feedback!

**Comment by dawholl** [comment]
issue fixed, closing this issue
