### ISSUE TITLE
FileShare Graph Connector finds nothing to index

### ISSUE THREAD

**Issue by mhomol** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#74]
## FileShare Graph Connector finds nothing to index

Hello!

I'm trying out the FileShare Graph Connector on my dev tenant and personal Azure VM.  To start, I have created a File Share on the VM that looks like this (should all be supported document types):

![Screen Shot 2020-07-01 at 3 11 14 PM](https://user-images.githubusercontent.com/680566/86282597-8e56a200-bbad-11ea-995d-370fafaf4efe.png)

Then I installed the Power BI Gateway on that same VM and first tested a connection from Power BI to the shared folder which connected fine.  So finally I came out to my dev tenant and added the FileShare connector to the same, path.  The test connection worked fine.  Here it is in the list of connectors:

![Screen Shot 2020-07-01 at 3 11 37 PM](https://user-images.githubusercontent.com/680566/86282595-8e56a200-bbad-11ea-9c5c-d4a62c32b038.png)

However, as you can see, it says it found nothing to index, but I also get no errors.  At one point, I was getting an error about the format of one of the documents in the folder, so I removed that file.  Now I get no errors, but also nothing successfully indexed.  Any help you can lend in what I should try next would be greatly appreciated.  Here are snapshots of the Details of the connector and the error tab as well:

![Screen Shot 2020-07-01 at 3 11 56 PM](https://user-images.githubusercontent.com/680566/86282593-8dbe0b80-bbad-11ea-95b5-b7a812245349.png)

![Screen Shot 2020-07-01 at 3 12 06 PM](https://user-images.githubusercontent.com/680566/86282590-8c8cde80-bbad-11ea-9fa6-292680932d66.png)

**Comment by monaray97** [comment]
Hi @mhomol, sorry you are having trouble. Please contact MicrosoftGraphConnectorsFeedback@service.microsoft.com with your issue and include your tenant ID so our team can support you.
