### ISSUE TITLE
Acronym is working in office.com now

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#75]
[Enter feedback here]
I just tested today an i can see that Acronyms are working from Office.com as well. is it because my tenant is part of the targeted release? If yes, can you please update the documentation and FAQ section now with expected date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd51764-80a7-b404-50bd-b492b193dab2
* Version Independent ID: 62a6858b-81a3-bafa-4bcc-3bb2a951c654
* Content: [Manage Acronym answers in Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms)
* Content Source: [MicrosoftSearch/manage-acronyms.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-acronyms.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by RakeshMSFT** [comment]
Hi @dhawal16,

We have recently enabled Acronyms to targeted release customers on SharePoint and we are in the process of rolling out to customers world wide. Thanks for reaching out to us, we have noted your feedback. The team is working on updating the documentation and FAQ section.
