### ISSUE TITLE
The new Adaptive Cards Templating binding syntax is not working

### ISSUE THREAD

**Issue by faisal-imam** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#76]
As per [this page,](https://docs.microsoft.com/en-us/adaptive-cards/templating/) the binding syntax for Adaptive cards is changed recently from {...} to ${...}. This new syntax doesn't seem to be available though in Microsoft Search and any dollar sign ($) inserted before the curly brackets in the layout JSON is inserted as-is in the search results display.

**Comment by jypal6** [comment]
Will update the documentation for this.

**Comment by jypal6** [comment]
Correction- Microsoft Search has not yet upgraded to the latest Adaptive card library and hence this syntax change is not yet updated in documentation. We are in the process of migrating and we will change the documentation once that is done.

**Comment by faisal-imam** [comment]
If I use the `"version": "1.2"` in the Adaptive card, the `${..}` syntax works fine and I'm able to reference all the properties in the search schema using this syntax. 

The problem is that whenever I try to reference a multi-valued property (multi-valued strings are represented as array of strings in JSON) using the `${$data}` syntax, it doesn't recognize the syntax and says that: **The properties used while generating JSON are not valid**.  

Here is a sample code which works just fine in [Adaptive Card Designer](https://adaptivecards.io/designer):

`{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "$data": "${employees}",
                    "text": "${$data}"
                }
            ]
        }           
    ],	
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}`

and produces the following output:

`{
    "employees": ["John", "Stuart", "Matt"]    
}`

but if I use the same Adaptive Card while providing the Layout for a **Result Type** in Microsoft Search, it gives me the error message I mentioned above.

**Comment by jypal6** [comment]
There are two aspects of the issue here:

1. Microsoft Search has not upgraded to the Adaptive card 1.2 version yet and hence ${employee}  syntax should not be used in **Result Type** setup. 

2. Multi-valued string support in Result type:We have taken a note of the need to support this and will provide this support.

**Comment by faisal-imam** [comment]
Is there an ETA on the support for Adaptive card version 1.2 for Microsoft Search?

**Comment by jypal6** [comment]
The current ETA is end of November 2020.

**Comment by jypal6** [comment]
Update to the rollout of Adaptive card version 1.2: Due to some technical issues the rollout has been delayed and is expected to happen in Jan 2021.

**Comment by jypal6** [comment]
Adaptive card 1.2 version is now supported in Microsoft search results page.
