### ISSUE TITLE
File Share Connector for Microsoft Search doesn't exist as per documentation released by Microsoft 

### ISSUE THREAD

**Issue by prawnz** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#77]
I was looking into https://docs.microsoft.com/en-us/microsoftsearch/file-share-connector and in a targeted release tenant it doesn't seem to have the file share data source indicating misalignment of the documentation with what is available as shown 
![image](https://user-images.githubusercontent.com/3827044/87390883-4f2c4600-c5dc-11ea-9333-0028616551a1.png)

**Comment by monaray97** [comment]
@prawnz, thank you for your comment. The documentation should be up to date now.
