### ISSUE TITLE
pattern

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#78]
In this question - Q: How do users trigger Acronyms answers?

What are the supported query patterns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd51764-80a7-b404-50bd-b492b193dab2
* Version Independent ID: 62a6858b-81a3-bafa-4bcc-3bb2a951c654
* Content: [Manage Acronym answers in Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms)
* Content Source: [MicrosoftSearch/manage-acronyms.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/manage-acronyms.md)
* Service: **mssearch**
* GitHub Login: @jeffkizn
* Microsoft Alias: **jeffkizn**

**Comment by RakeshMSFT** [comment]
Hi @danmyhre 
Thanks for reaching out to us. You can find all supported query patterns here on this link- https://docs.microsoft.com/en-us/microsoftsearch/manage-acronyms. E.g. You can query- What is DNN‏‏‎, Define DNN‏‏‎, DNN‏‏‎ definition, Expand DNN‏‏‎, DNN‏‏‎ expansion, Meaning of DNN‏‏‎, DNN‏‏‎ means etc. to search for the meaning of DNN.
