### ISSUE TITLE
Clarify supported MS Search functionality for GCC Moderate / GCC High?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#79]
Can we please add clarification in the FAQ (or Service Descriptions) for what functionality is/isn't available for Microsoft Search within our sovereign cloud implementation for GCC Moderate and GCC High and DOD environments?

There appears to be partial functionality for GCC Moderate, but not clear what is supported/works vs what is not available. Many Federal, State, and Local Public Sector customers use GCC Moderate and are very interested in Microsoft Search functionality but do not have clarity regarding what is available/functionality within their environment.

**Comment by jeffkizn** [comment]
Microsoft Search has not been released in GCC, GCC-H, or US DoD environments. There is currently an issue in which some GCC customers may be able to see the Microsoft Search admin portal, but the underlying functionality of the product does not work. We will look to make this clearer in the documentation as well as provide a clear roadmap for Microsoft Search in these environments.
