### ISSUE TITLE
Information on extending / buying search quota

### ISSUE THREAD

**Issue by marcoschmucker** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#80]
On two tenants (Targeted Release) we are no longer able to configure connections:

Error message:
" Your organization have no allocated quota. You will need to purchase quota so that you can add new connections. "

We cannot find documentation on how to purchase quota for search service.

**Comment by monaray97** [comment]
Hi @marcoschmucker, sorry you are running into this issue. Please send an email to MicrosoftGraphConnectorsFeedback@service.microsoft.com including the 2 tenant IDs and screenshots of this behavior. Also make sure to mention that you had raised an issue in the docs as well. Someone from our team will get back to you and help resolve this issue. In the meantime, let me know if you have any questions.
