### ISSUE TITLE
Inconsistent statements about SharePoint search verticals 

### ISSUE THREAD

**Issue by TristanJamesBall** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#81]
This page says both: "You can create search verticals and result types to customize the search results that users see when they search in Microsoft SharePoint, Microsoft Office, and Microsoft Search in Bing" and "You can’t create a vertical for content that resides in SharePoint."

These statements would appear to contradict each other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-us/microsoftsearch/customize-search-page)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @jypal
* Microsoft Alias: **jypal6**

**Comment by jypal6** [comment]
SharePoint in this paragraph is being used in two different context. In the first the search page in Microsoft Search is discussed where Connector data can be shown. In the second, SharePoint as a content source is referred. For the latter, the admins do not have the same capability as they do for Connectors and that is being called out here.

**Comment by jypal6** [comment]
I believe this issue can be closed now.
