### ISSUE TITLE
Error when loading Graph Connectors

### ISSUE THREAD

**Issue by KennethBWSong** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#86]
Can not see any created connectors under my own tenant.
![image](https://user-images.githubusercontent.com/63089166/93426076-e5872b80-f8ed-11ea-99ab-ea7422129029.png)

The error messages said "Error when loading connectors".

**Comment by monaray97** [comment]
@KennethBWSong Sorry to hear you are having trouble seeing your connections. Have you tried refreshing the page? If the error still persists, please contact MicrosoftGraphConnectorsFeedback@service.microsoft.com and we will help with the issue.

**Comment by KennethBWSong** [comment]
@monaray97 Thank you for your reply! The error persists no matter how many times I refresh the page. Now I have sent an email to MicrosoftGraphConnectorsFeedback@service.microsoft.com to ask for help. Thank you again for your suggestion!
