### ISSUE TITLE
Customizing custom Microsoft Search verticals?

### ISSUE THREAD

**Issue by virtualducttape** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#89]
Are there any plans to allow for further customization of the custom search verticals?

In particular, it would be nice to customize:

-  "No Results" page text

- Bookmarks (and other "Answers") that would appear in a given vertical

- Additional context/information around the vertical

The specific use case we're considering is the ability for a user to submit a Service Now ticket in the event that they cannot find the Service Now result they are looking for in the Microsoft Search custom vertical. Currently the user could submit feedback via the O365 feedback mechanism, but this would go to O365 admins, who may not be the same people as the Service Now admins.

As more and more custom verticals are created, I imagine the need to provide some degree of additional information/functionality to the user within that vertical will increase.

**Comment by jypal6** [comment]
Thank you for raising this ask. Can you please submit this feedback via the Microsoft Search admin center/vertical page feedback and we can look into this further by connecting with you. You will see a 'Give feedback' option on the bottom right of the page.
