### ISSUE TITLE
Required Privileges

### ISSUE THREAD

**Issue by Mindzweeper** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#9]
What is the minimum set of privileges required to perform the documented steps?  Does it require tenant admin, or is there a role scoped specifically to Microsoft Search?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cfd814-0551-a1c9-1001-0bdf2a028c6b
* Version Independent ID: d6ee9a96-33f1-0dcb-5bb7-f5695a3a1987
* Content: [Quick set up for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/quick-set-up)
* Content Source: [MicrosoftSearch/quick-set-up.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/quick-set-up.md)
* Service: **mssearch**
* GitHub Login: @dawholl
* Microsoft Alias: **dawholl**

**Comment by WendyStidmon** [comment]
![image](https://user-images.githubusercontent.com/51454343/59049432-cbcaed80-883c-11e9-8108-59348c19fc57.png)

**Comment by adefowler** [comment]
Hi, Mindzweeper. If you're using the legacy Microsoft Search in Bing admin portal, then you need to be a global admin (tenant admin). If you are administering Microsoft Search from the Microsoft 365 admin center: Settings > Microsoft Search, then you can be a Search admin or a Search editor. Those are two new roles that we've created to support Microsoft Search.
