### ISSUE TITLE
Recommend making "You can’t create a vertical for content that resides in SharePoint" into a highlighted note

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#96]
I spent about four days trying to figure out why I couldn't select SharePoint content as a content sources for the new verticals and result types. I reviewed this page and finally found "You can’t create a vertical for content that resides in SharePoint". Please move this to the top of the page and highlight it as a note/warning/whatever, just make it blatantly apparent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce38a86-b4a9-9c13-f772-4f79b8ecd0cb
* Version Independent ID: 933c3664-1f7f-680a-fb5f-5576bed5943c
* Content: [Customize the Microsoft Search page](https://docs.microsoft.com/en-us/microsoftsearch/customize-search-page)
* Content Source: [MicrosoftSearch/customize-search-page.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/customize-search-page.md)
* Service: **mssearch**
* GitHub Login: @jypal
* Microsoft Alias: **jeffkizn**

**Comment by jypal6** [comment]
Thanks for the feedback. The page will be updated.
